/*
 *  Warning: Do not edit this file.  It was automatically
 *  generated by 'beam_makeops' on Fri Jul 31 14:49:33 2009.
 */

#ifndef __OPCODES_H__
#define __OPCODES_H__

#define BEAM_FORMAT_NUMBER 0
#define MAX_GENERIC_OPCODE 148
#define NUM_GENERIC_OPS 325
#define NUM_SPECIFIC_OPS 432

#ifdef ARCH_64
#  define BEAM_LOOSE_MASK 0x1FFFUL
#  define BEAM_TIGHT_MASK 0x1FF8UL
#  define BEAM_LOOSE_SHIFT 16
#  define BEAM_TIGHT_SHIFT 16
#else
#  define BEAM_LOOSE_MASK 0xFFF
#  define BEAM_TIGHT_MASK 0xFFC
#  define BEAM_LOOSE_SHIFT 16
#  define BEAM_TIGHT_SHIFT 10
#endif

/*
 * The following operand types for generic instructions
 * occur in beam files.
 */

#define TAG_u 0
#define TAG_i 1
#define TAG_a 2
#define TAG_x 3
#define TAG_y 4
#define TAG_f 5
#define TAG_h 6
#define TAG_z 7

/*
 * The following operand types are only used in the loader.
 */

#define TAG_n 8
#define TAG_p 9
#define TAG_r 10
#define TAG_v 11
#define TAG_l 12
#define TAG_q 13

#define BEAM_NUM_TAGS 14

#define TOP_call 0
#define TOP_commit 1
#define TOP_end 2
#define TOP_fail 3
#define TOP_is_bif 4
#define TOP_is_eq 5
#define TOP_is_func 6
#define TOP_is_not_bif 7
#define TOP_is_op 8
#define TOP_is_same_var 9
#define TOP_is_type 10
#define TOP_new_instr 11
#define TOP_next_arg 12
#define TOP_next_instr 13
#define TOP_pred 14
#define TOP_rest_args 15
#define TOP_set_var_next_arg 16
#define TOP_store_op 17
#define TOP_store_type 18
#define TOP_store_val 19
#define TOP_store_var 20
#define TOP_try_me_else 21
#define NUM_TOPS 22

#define TE_MAX_VARS 8

extern char tag_to_letter[];
extern Uint op_transform[];

#define op_allocate_tt 0
#define op_allocate_heap_III 1
#define op_allocate_heap_zero_III 2
#define op_allocate_init_tIy 3
#define op_allocate_zero_tt 4
#define op_apply_I 5
#define op_apply_bif 6
#define op_apply_last_IP 7
#define op_badarg_j 8
#define op_badmatch_s 9
#define op_bif1_fbsd 10
#define op_bif1_body_bsd 11
#define op_bs_context_to_binary_r 12
#define op_bs_context_to_binary_x 13
#define op_bs_context_to_binary_y 14
#define op_bs_init_writable 15
#define op_bs_put_string_II 16
#define op_bs_test_tail_imm2_frI 17
#define op_bs_test_tail_imm2_fxI 18
#define op_bs_test_unit_frI 19
#define op_bs_test_unit_fxI 20
#define op_bs_test_unit8_fr 21
#define op_bs_test_unit8_fx 22
#define op_bs_test_zero_tail2_fr 23
#define op_bs_test_zero_tail2_fx 24
#define op_call_bif0_e 25
#define op_call_bif1_e 26
#define op_call_bif2_e 27
#define op_call_bif3_e 28
#define op_call_error_handler 29
#define op_call_traced_function 30
#define op_case_end_s 31
#define op_catch_yf 32
#define op_catch_end_y 33
#define op_continue_exit 34
#define op_deallocate_I 35
#define op_deallocate_return_P 36
#define op_error_action_code 37
#define op_extract_next_element_x 38
#define op_extract_next_element_y 39
#define op_extract_next_element2_x 40
#define op_extract_next_element2_y 41
#define op_extract_next_element3_x 42
#define op_extract_next_element3_y 43
#define op_fclearerror 44
#define op_fconv_dl 45
#define op_fmove_ql 46
#define op_fmove_dl 47
#define op_fmove_new_ld 48
#define op_get_list_rrx 49
#define op_get_list_rry 50
#define op_get_list_rxr 51
#define op_get_list_rxx 52
#define op_get_list_rxy 53
#define op_get_list_ryr 54
#define op_get_list_ryx 55
#define op_get_list_ryy 56
#define op_get_list_xrx 57
#define op_get_list_xry 58
#define op_get_list_xxr 59
#define op_get_list_xxx 60
#define op_get_list_xxy 61
#define op_get_list_xyr 62
#define op_get_list_xyx 63
#define op_get_list_xyy 64
#define op_get_list_yrx 65
#define op_get_list_yry 66
#define op_get_list_yxr 67
#define op_get_list_yxx 68
#define op_get_list_yxy 69
#define op_get_list_yyr 70
#define op_get_list_yyx 71
#define op_get_list_yyy 72
#define op_hipe_call_count 73
#define op_hipe_trap_call 74
#define op_hipe_trap_call_closure 75
#define op_hipe_trap_resume 76
#define op_hipe_trap_return 77
#define op_hipe_trap_throw 78
#define op_i_apply 79
#define op_i_apply_fun 80
#define op_i_apply_fun_last_P 81
#define op_i_apply_fun_only 82
#define op_i_apply_last_P 83
#define op_i_apply_only 84
#define op_i_band_jId 85
#define op_i_bif2_fbd 86
#define op_i_bif2_body_bd 87
#define op_i_bor_jId 88
#define op_i_bs_add_jId 89
#define op_i_bs_append_jIIId 90
#define op_i_bs_bits_to_bytes_rjd 91
#define op_i_bs_bits_to_bytes_xjd 92
#define op_i_bs_bits_to_bytes_yjd 93
#define op_i_bs_get_binary2_frIsId 94
#define op_i_bs_get_binary2_fxIsId 95
#define op_i_bs_get_binary_all2_frIId 96
#define op_i_bs_get_binary_all2_fxIId 97
#define op_i_bs_get_binary_all_reuse_rfI 98
#define op_i_bs_get_binary_all_reuse_xfI 99
#define op_i_bs_get_binary_imm2_frIIId 100
#define op_i_bs_get_binary_imm2_fxIIId 101
#define op_i_bs_get_float2_frIsId 102
#define op_i_bs_get_float2_fxIsId 103
#define op_i_bs_get_integer_fIId 104
#define op_i_bs_get_integer_16_rfd 105
#define op_i_bs_get_integer_16_xfd 106
#define op_i_bs_get_integer_32_rfId 107
#define op_i_bs_get_integer_32_xfId 108
#define op_i_bs_get_integer_8_rfd 109
#define op_i_bs_get_integer_8_xfd 110
#define op_i_bs_get_integer_imm_rIIfId 111
#define op_i_bs_get_integer_imm_xIIfId 112
#define op_i_bs_get_integer_small_imm_rIfId 113
#define op_i_bs_get_integer_small_imm_xIfId 114
#define op_i_bs_get_utf16_rfId 115
#define op_i_bs_get_utf16_xfId 116
#define op_i_bs_get_utf8_rfd 117
#define op_i_bs_get_utf8_xfd 118
#define op_i_bs_init_IId 119
#define op_i_bs_init_bits_IId 120
#define op_i_bs_init_bits_fail_rjId 121
#define op_i_bs_init_bits_fail_xjId 122
#define op_i_bs_init_bits_fail_yjId 123
#define op_i_bs_init_bits_fail_heap_IjId 124
#define op_i_bs_init_bits_heap_IIId 125
#define op_i_bs_init_fail_rjId 126
#define op_i_bs_init_fail_xjId 127
#define op_i_bs_init_fail_yjId 128
#define op_i_bs_init_fail_heap_IjId 129
#define op_i_bs_init_heap_IIId 130
#define op_i_bs_init_heap_bin_IId 131
#define op_i_bs_init_heap_bin_heap_IIId 132
#define op_i_bs_match_string_rfII 133
#define op_i_bs_match_string_xfII 134
#define op_i_bs_private_append_jId 135
#define op_i_bs_put_utf16_jIs 136
#define op_i_bs_put_utf8_js 137
#define op_i_bs_restore2_rI 138
#define op_i_bs_restore2_xI 139
#define op_i_bs_save2_rI 140
#define op_i_bs_save2_xI 141
#define op_i_bs_skip_bits2_frxI 142
#define op_i_bs_skip_bits2_fryI 143
#define op_i_bs_skip_bits2_fxrI 144
#define op_i_bs_skip_bits2_fxxI 145
#define op_i_bs_skip_bits2_fxyI 146
#define op_i_bs_skip_bits_all2_frI 147
#define op_i_bs_skip_bits_all2_fxI 148
#define op_i_bs_skip_bits_imm2_frI 149
#define op_i_bs_skip_bits_imm2_fxI 150
#define op_i_bs_start_match2_rfIId 151
#define op_i_bs_start_match2_xfIId 152
#define op_i_bs_start_match2_yfIId 153
#define op_i_bs_utf16_size_sd 154
#define op_i_bs_utf8_size_sd 155
#define op_i_bs_validate_unicode_js 156
#define op_i_bs_validate_unicode_retract_j 157
#define op_i_bsl_jId 158
#define op_i_bsr_jId 159
#define op_i_bxor_jId 160
#define op_i_call_f 161
#define op_i_call_ext_e 162
#define op_i_call_ext_last_eP 163
#define op_i_call_ext_only_e 164
#define op_i_call_fun_I 165
#define op_i_call_fun_last_IP 166
#define op_i_call_last_fP 167
#define op_i_call_only_f 168
#define op_i_count_breakpoint 169
#define op_i_debug_breakpoint 170
#define op_i_element_jssd 171
#define op_i_fadd_lll 172
#define op_i_fast_element_jIsd 173
#define op_i_fcheckerror 174
#define op_i_fdiv_lll 175
#define op_i_fetch_rx 176
#define op_i_fetch_ry 177
#define op_i_fetch_xr 178
#define op_i_fetch_xx 179
#define op_i_fetch_xy 180
#define op_i_fetch_yr 181
#define op_i_fetch_yx 182
#define op_i_fetch_yy 183
#define op_i_fetch_rc 184
#define op_i_fetch_xc 185
#define op_i_fetch_yc 186
#define op_i_fetch_cr 187
#define op_i_fetch_cx 188
#define op_i_fetch_cy 189
#define op_i_fetch_cc 190
#define op_i_fetch_ss 191
#define op_i_fmul_lll 192
#define op_i_fnegate_ll 193
#define op_i_fsub_lll 194
#define op_i_func_info_IaaI 195
#define op_i_gc_bif1_jIsId 196
#define op_i_get_sd 197
#define op_i_get_tuple_element_rPr 198
#define op_i_get_tuple_element_rPx 199
#define op_i_get_tuple_element_rPy 200
#define op_i_get_tuple_element_xPr 201
#define op_i_get_tuple_element_xPx 202
#define op_i_get_tuple_element_xPy 203
#define op_i_get_tuple_element_yPr 204
#define op_i_get_tuple_element_yPx 205
#define op_i_get_tuple_element_yPy 206
#define op_i_global_cons 207
#define op_i_global_copy 208
#define op_i_global_tuple 209
#define op_i_hibernate 210
#define op_i_int_bnot_jsId 211
#define op_i_int_div_jId 212
#define op_i_is_eq_f 213
#define op_i_is_eq_exact_f 214
#define op_i_is_eq_immed_frc 215
#define op_i_is_eq_immed_fxc 216
#define op_i_is_eq_immed_fyc 217
#define op_i_is_ge_f 218
#define op_i_is_lt_f 219
#define op_i_is_ne_f 220
#define op_i_is_ne_exact_f 221
#define op_i_jump_on_val_sfII 222
#define op_i_jump_on_val_zero_sfI 223
#define op_i_loop_rec_fr 224
#define op_i_m_div_jId 225
#define op_i_make_fun_It 226
#define op_i_minus_jId 227
#define op_i_move_call_crf 228
#define op_i_move_call_ext_cre 229
#define op_i_move_call_ext_last_ePcr 230
#define op_i_move_call_ext_only_ecr 231
#define op_i_move_call_last_fPcr 232
#define op_i_move_call_only_fcr 233
#define op_i_mtrace_breakpoint 234
#define op_i_new_bs_put_binary_jsIs 235
#define op_i_new_bs_put_binary_all_jsI 236
#define op_i_new_bs_put_binary_imm_jIs 237
#define op_i_new_bs_put_float_jsIs 238
#define op_i_new_bs_put_float_imm_jIIs 239
#define op_i_new_bs_put_integer_jsIs 240
#define op_i_new_bs_put_integer_imm_jIIs 241
#define op_i_plus_jId 242
#define op_i_put_tuple_Anr 243
#define op_i_put_tuple_Anx 244
#define op_i_put_tuple_Arx 245
#define op_i_put_tuple_Ary 246
#define op_i_put_tuple_Axr 247
#define op_i_put_tuple_Axx 248
#define op_i_put_tuple_Axy 249
#define op_i_put_tuple_Ayr 250
#define op_i_put_tuple_Ayx 251
#define op_i_put_tuple_Ayy 252
#define op_i_put_tuple_Acr 253
#define op_i_put_tuple_Acx 254
#define op_i_put_tuple_Acy 255
#define op_i_put_tuple_only_Ad 256
#define op_i_rem_jId 257
#define op_i_return_to_trace 258
#define op_i_select_big_sf 259
#define op_i_select_float_sfI 260
#define op_i_select_tuple_arity_sfI 261
#define op_i_select_val_sfI 262
#define op_i_times_jId 263
#define op_i_trace_breakpoint 264
#define op_i_trim_I 265
#define op_i_wait_error 266
#define op_i_wait_error_locked 267
#define op_i_wait_timeout_fI 268
#define op_i_wait_timeout_fs 269
#define op_i_wait_timeout_locked_fI 270
#define op_i_wait_timeout_locked_fs 271
#define op_i_yield 272
#define op_if_end 273
#define op_init_y 274
#define op_init2_yy 275
#define op_init3_yyy 276
#define op_int_code_end 277
#define op_is_atom_fr 278
#define op_is_atom_fx 279
#define op_is_atom_fy 280
#define op_is_binary_fr 281
#define op_is_binary_fx 282
#define op_is_binary_fy 283
#define op_is_bitstring_fr 284
#define op_is_bitstring_fx 285
#define op_is_bitstring_fy 286
#define op_is_boolean_fr 287
#define op_is_boolean_fx 288
#define op_is_boolean_fy 289
#define op_is_float_fr 290
#define op_is_float_fx 291
#define op_is_float_fy 292
#define op_is_function_fr 293
#define op_is_function_fx 294
#define op_is_function_fy 295
#define op_is_function2_fss 296
#define op_is_integer_fr 297
#define op_is_integer_fx 298
#define op_is_integer_fy 299
#define op_is_integer_allocate_frII 300
#define op_is_integer_allocate_fxII 301
#define op_is_list_fr 302
#define op_is_list_fx 303
#define op_is_list_fy 304
#define op_is_nil_fr 305
#define op_is_nil_fx 306
#define op_is_nil_fy 307
#define op_is_non_empty_list_test_heap_frII 308
#define op_is_nonempty_list_fr 309
#define op_is_nonempty_list_fx 310
#define op_is_nonempty_list_fy 311
#define op_is_nonempty_list_allocate_frII 312
#define op_is_nonempty_list_allocate_fxII 313
#define op_is_number_fr 314
#define op_is_number_fx 315
#define op_is_number_fy 316
#define op_is_pid_fr 317
#define op_is_pid_fx 318
#define op_is_pid_fy 319
#define op_is_port_fr 320
#define op_is_port_fx 321
#define op_is_port_fy 322
#define op_is_reference_fr 323
#define op_is_reference_fx 324
#define op_is_reference_fy 325
#define op_is_tuple_fr 326
#define op_is_tuple_fx 327
#define op_is_tuple_fy 328
#define op_is_tuple_of_arity_frA 329
#define op_is_tuple_of_arity_fxA 330
#define op_is_tuple_of_arity_fyA 331
#define op_jump_f 332
#define op_label_L 333
#define op_loop_rec_end_f 334
#define op_move_nr 335
#define op_move_nx 336
#define op_move_rx 337
#define op_move_ry 338
#define op_move_xr 339
#define op_move_xx 340
#define op_move_xy 341
#define op_move_yr 342
#define op_move_yx 343
#define op_move_yy 344
#define op_move_cr 345
#define op_move_cx 346
#define op_move_cy 347
#define op_move_sd 348
#define op_move2_xyxy 349
#define op_move2_yxyx 350
#define op_move_call_xrf 351
#define op_move_call_yrf 352
#define op_move_call_last_xrfP 353
#define op_move_call_last_yrfP 354
#define op_move_call_only_xrf 355
#define op_move_deallocate_return_nrP 356
#define op_move_deallocate_return_xrP 357
#define op_move_deallocate_return_yrP 358
#define op_move_deallocate_return_crP 359
#define op_move_return_nr 360
#define op_move_return_xr 361
#define op_move_return_cr 362
#define op_node_r 363
#define op_node_x 364
#define op_node_y 365
#define op_normal_exit 366
#define op_put_n 367
#define op_put_r 368
#define op_put_x 369
#define op_put_y 370
#define op_put_c 371
#define op_put_list_rnx 372
#define op_put_list_rxr 373
#define op_put_list_rxx 374
#define op_put_list_ryx 375
#define op_put_list_xnx 376
#define op_put_list_xrr 377
#define op_put_list_xxr 378
#define op_put_list_xxx 379
#define op_put_list_xyx 380
#define op_put_list_ynx 381
#define op_put_list_yrr 382
#define op_put_list_yrx 383
#define op_put_list_yxx 384
#define op_put_list_yyr 385
#define op_put_list_yyx 386
#define op_put_list_rcr 387
#define op_put_list_rcx 388
#define op_put_list_rcy 389
#define op_put_list_xcr 390
#define op_put_list_xcx 391
#define op_put_list_xcy 392
#define op_put_list_ycr 393
#define op_put_list_ycx 394
#define op_put_list_ycy 395
#define op_put_list_cnr 396
#define op_put_list_cnx 397
#define op_put_list_crr 398
#define op_put_list_crx 399
#define op_put_list_cry 400
#define op_put_list_cxr 401
#define op_put_list_cxx 402
#define op_put_list_cxy 403
#define op_put_list_cyr 404
#define op_put_list_cyx 405
#define op_put_list_cyy 406
#define op_put_list_ssd 407
#define op_put_string_IId 408
#define op_raise_ss 409
#define op_remove_message 410
#define op_return 411
#define op_return_trace 412
#define op_self_r 413
#define op_self_x 414
#define op_self_y 415
#define op_send 416
#define op_set_tuple_element_sdP 417
#define op_system_limit_j 418
#define op_test_arity_frA 419
#define op_test_arity_fxA 420
#define op_test_arity_fyA 421
#define op_test_heap_II 422
#define op_test_heap_1_put_list_Iy 423
#define op_timeout 424
#define op_timeout_locked 425
#define op_too_old_compiler 426
#define op_try_case_end_s 427
#define op_try_end_y 428
#define op_wait_f 429
#define op_wait_locked_f 430
#define op_wait_unlocked_f 431

#define NUMBER_OF_OPCODES 432
#define op_count_allocate_tt 432
#define op_count_allocate_heap_III 433
#define op_count_allocate_heap_zero_III 434
#define op_count_allocate_init_tIy 435
#define op_count_allocate_zero_tt 436
#define op_count_apply_I 437
#define op_count_apply_bif 438
#define op_count_apply_last_IP 439
#define op_count_badarg_j 440
#define op_count_badmatch_s 441
#define op_count_bif1_fbsd 442
#define op_count_bif1_body_bsd 443
#define op_count_bs_context_to_binary_r 444
#define op_count_bs_context_to_binary_x 445
#define op_count_bs_context_to_binary_y 446
#define op_count_bs_init_writable 447
#define op_count_bs_put_string_II 448
#define op_count_bs_test_tail_imm2_frI 449
#define op_count_bs_test_tail_imm2_fxI 450
#define op_count_bs_test_unit_frI 451
#define op_count_bs_test_unit_fxI 452
#define op_count_bs_test_unit8_fr 453
#define op_count_bs_test_unit8_fx 454
#define op_count_bs_test_zero_tail2_fr 455
#define op_count_bs_test_zero_tail2_fx 456
#define op_count_call_bif0_e 457
#define op_count_call_bif1_e 458
#define op_count_call_bif2_e 459
#define op_count_call_bif3_e 460
#define op_count_call_error_handler 461
#define op_count_call_traced_function 462
#define op_count_case_end_s 463
#define op_count_catch_yf 464
#define op_count_catch_end_y 465
#define op_count_continue_exit 466
#define op_count_deallocate_I 467
#define op_count_deallocate_return_P 468
#define op_count_error_action_code 469
#define op_count_extract_next_element_x 470
#define op_count_extract_next_element_y 471
#define op_count_extract_next_element2_x 472
#define op_count_extract_next_element2_y 473
#define op_count_extract_next_element3_x 474
#define op_count_extract_next_element3_y 475
#define op_count_fclearerror 476
#define op_count_fconv_dl 477
#define op_count_fmove_ql 478
#define op_count_fmove_dl 479
#define op_count_fmove_new_ld 480
#define op_count_get_list_rrx 481
#define op_count_get_list_rry 482
#define op_count_get_list_rxr 483
#define op_count_get_list_rxx 484
#define op_count_get_list_rxy 485
#define op_count_get_list_ryr 486
#define op_count_get_list_ryx 487
#define op_count_get_list_ryy 488
#define op_count_get_list_xrx 489
#define op_count_get_list_xry 490
#define op_count_get_list_xxr 491
#define op_count_get_list_xxx 492
#define op_count_get_list_xxy 493
#define op_count_get_list_xyr 494
#define op_count_get_list_xyx 495
#define op_count_get_list_xyy 496
#define op_count_get_list_yrx 497
#define op_count_get_list_yry 498
#define op_count_get_list_yxr 499
#define op_count_get_list_yxx 500
#define op_count_get_list_yxy 501
#define op_count_get_list_yyr 502
#define op_count_get_list_yyx 503
#define op_count_get_list_yyy 504
#define op_count_hipe_call_count 505
#define op_count_hipe_trap_call 506
#define op_count_hipe_trap_call_closure 507
#define op_count_hipe_trap_resume 508
#define op_count_hipe_trap_return 509
#define op_count_hipe_trap_throw 510
#define op_count_i_apply 511
#define op_count_i_apply_fun 512
#define op_count_i_apply_fun_last_P 513
#define op_count_i_apply_fun_only 514
#define op_count_i_apply_last_P 515
#define op_count_i_apply_only 516
#define op_count_i_band_jId 517
#define op_count_i_bif2_fbd 518
#define op_count_i_bif2_body_bd 519
#define op_count_i_bor_jId 520
#define op_count_i_bs_add_jId 521
#define op_count_i_bs_append_jIIId 522
#define op_count_i_bs_bits_to_bytes_rjd 523
#define op_count_i_bs_bits_to_bytes_xjd 524
#define op_count_i_bs_bits_to_bytes_yjd 525
#define op_count_i_bs_get_binary2_frIsId 526
#define op_count_i_bs_get_binary2_fxIsId 527
#define op_count_i_bs_get_binary_all2_frIId 528
#define op_count_i_bs_get_binary_all2_fxIId 529
#define op_count_i_bs_get_binary_all_reuse_rfI 530
#define op_count_i_bs_get_binary_all_reuse_xfI 531
#define op_count_i_bs_get_binary_imm2_frIIId 532
#define op_count_i_bs_get_binary_imm2_fxIIId 533
#define op_count_i_bs_get_float2_frIsId 534
#define op_count_i_bs_get_float2_fxIsId 535
#define op_count_i_bs_get_integer_fIId 536
#define op_count_i_bs_get_integer_16_rfd 537
#define op_count_i_bs_get_integer_16_xfd 538
#define op_count_i_bs_get_integer_32_rfId 539
#define op_count_i_bs_get_integer_32_xfId 540
#define op_count_i_bs_get_integer_8_rfd 541
#define op_count_i_bs_get_integer_8_xfd 542
#define op_count_i_bs_get_integer_imm_rIIfId 543
#define op_count_i_bs_get_integer_imm_xIIfId 544
#define op_count_i_bs_get_integer_small_imm_rIfId 545
#define op_count_i_bs_get_integer_small_imm_xIfId 546
#define op_count_i_bs_get_utf16_rfId 547
#define op_count_i_bs_get_utf16_xfId 548
#define op_count_i_bs_get_utf8_rfd 549
#define op_count_i_bs_get_utf8_xfd 550
#define op_count_i_bs_init_IId 551
#define op_count_i_bs_init_bits_IId 552
#define op_count_i_bs_init_bits_fail_rjId 553
#define op_count_i_bs_init_bits_fail_xjId 554
#define op_count_i_bs_init_bits_fail_yjId 555
#define op_count_i_bs_init_bits_fail_heap_IjId 556
#define op_count_i_bs_init_bits_heap_IIId 557
#define op_count_i_bs_init_fail_rjId 558
#define op_count_i_bs_init_fail_xjId 559
#define op_count_i_bs_init_fail_yjId 560
#define op_count_i_bs_init_fail_heap_IjId 561
#define op_count_i_bs_init_heap_IIId 562
#define op_count_i_bs_init_heap_bin_IId 563
#define op_count_i_bs_init_heap_bin_heap_IIId 564
#define op_count_i_bs_match_string_rfII 565
#define op_count_i_bs_match_string_xfII 566
#define op_count_i_bs_private_append_jId 567
#define op_count_i_bs_put_utf16_jIs 568
#define op_count_i_bs_put_utf8_js 569
#define op_count_i_bs_restore2_rI 570
#define op_count_i_bs_restore2_xI 571
#define op_count_i_bs_save2_rI 572
#define op_count_i_bs_save2_xI 573
#define op_count_i_bs_skip_bits2_frxI 574
#define op_count_i_bs_skip_bits2_fryI 575
#define op_count_i_bs_skip_bits2_fxrI 576
#define op_count_i_bs_skip_bits2_fxxI 577
#define op_count_i_bs_skip_bits2_fxyI 578
#define op_count_i_bs_skip_bits_all2_frI 579
#define op_count_i_bs_skip_bits_all2_fxI 580
#define op_count_i_bs_skip_bits_imm2_frI 581
#define op_count_i_bs_skip_bits_imm2_fxI 582
#define op_count_i_bs_start_match2_rfIId 583
#define op_count_i_bs_start_match2_xfIId 584
#define op_count_i_bs_start_match2_yfIId 585
#define op_count_i_bs_utf16_size_sd 586
#define op_count_i_bs_utf8_size_sd 587
#define op_count_i_bs_validate_unicode_js 588
#define op_count_i_bs_validate_unicode_retract_j 589
#define op_count_i_bsl_jId 590
#define op_count_i_bsr_jId 591
#define op_count_i_bxor_jId 592
#define op_count_i_call_f 593
#define op_count_i_call_ext_e 594
#define op_count_i_call_ext_last_eP 595
#define op_count_i_call_ext_only_e 596
#define op_count_i_call_fun_I 597
#define op_count_i_call_fun_last_IP 598
#define op_count_i_call_last_fP 599
#define op_count_i_call_only_f 600
#define op_count_i_count_breakpoint 601
#define op_count_i_debug_breakpoint 602
#define op_count_i_element_jssd 603
#define op_count_i_fadd_lll 604
#define op_count_i_fast_element_jIsd 605
#define op_count_i_fcheckerror 606
#define op_count_i_fdiv_lll 607
#define op_count_i_fetch_rx 608
#define op_count_i_fetch_ry 609
#define op_count_i_fetch_xr 610
#define op_count_i_fetch_xx 611
#define op_count_i_fetch_xy 612
#define op_count_i_fetch_yr 613
#define op_count_i_fetch_yx 614
#define op_count_i_fetch_yy 615
#define op_count_i_fetch_rc 616
#define op_count_i_fetch_xc 617
#define op_count_i_fetch_yc 618
#define op_count_i_fetch_cr 619
#define op_count_i_fetch_cx 620
#define op_count_i_fetch_cy 621
#define op_count_i_fetch_cc 622
#define op_count_i_fetch_ss 623
#define op_count_i_fmul_lll 624
#define op_count_i_fnegate_ll 625
#define op_count_i_fsub_lll 626
#define op_count_i_func_info_IaaI 627
#define op_count_i_gc_bif1_jIsId 628
#define op_count_i_get_sd 629
#define op_count_i_get_tuple_element_rPr 630
#define op_count_i_get_tuple_element_rPx 631
#define op_count_i_get_tuple_element_rPy 632
#define op_count_i_get_tuple_element_xPr 633
#define op_count_i_get_tuple_element_xPx 634
#define op_count_i_get_tuple_element_xPy 635
#define op_count_i_get_tuple_element_yPr 636
#define op_count_i_get_tuple_element_yPx 637
#define op_count_i_get_tuple_element_yPy 638
#define op_count_i_global_cons 639
#define op_count_i_global_copy 640
#define op_count_i_global_tuple 641
#define op_count_i_hibernate 642
#define op_count_i_int_bnot_jsId 643
#define op_count_i_int_div_jId 644
#define op_count_i_is_eq_f 645
#define op_count_i_is_eq_exact_f 646
#define op_count_i_is_eq_immed_frc 647
#define op_count_i_is_eq_immed_fxc 648
#define op_count_i_is_eq_immed_fyc 649
#define op_count_i_is_ge_f 650
#define op_count_i_is_lt_f 651
#define op_count_i_is_ne_f 652
#define op_count_i_is_ne_exact_f 653
#define op_count_i_jump_on_val_sfII 654
#define op_count_i_jump_on_val_zero_sfI 655
#define op_count_i_loop_rec_fr 656
#define op_count_i_m_div_jId 657
#define op_count_i_make_fun_It 658
#define op_count_i_minus_jId 659
#define op_count_i_move_call_crf 660
#define op_count_i_move_call_ext_cre 661
#define op_count_i_move_call_ext_last_ePcr 662
#define op_count_i_move_call_ext_only_ecr 663
#define op_count_i_move_call_last_fPcr 664
#define op_count_i_move_call_only_fcr 665
#define op_count_i_mtrace_breakpoint 666
#define op_count_i_new_bs_put_binary_jsIs 667
#define op_count_i_new_bs_put_binary_all_jsI 668
#define op_count_i_new_bs_put_binary_imm_jIs 669
#define op_count_i_new_bs_put_float_jsIs 670
#define op_count_i_new_bs_put_float_imm_jIIs 671
#define op_count_i_new_bs_put_integer_jsIs 672
#define op_count_i_new_bs_put_integer_imm_jIIs 673
#define op_count_i_plus_jId 674
#define op_count_i_put_tuple_Anr 675
#define op_count_i_put_tuple_Anx 676
#define op_count_i_put_tuple_Arx 677
#define op_count_i_put_tuple_Ary 678
#define op_count_i_put_tuple_Axr 679
#define op_count_i_put_tuple_Axx 680
#define op_count_i_put_tuple_Axy 681
#define op_count_i_put_tuple_Ayr 682
#define op_count_i_put_tuple_Ayx 683
#define op_count_i_put_tuple_Ayy 684
#define op_count_i_put_tuple_Acr 685
#define op_count_i_put_tuple_Acx 686
#define op_count_i_put_tuple_Acy 687
#define op_count_i_put_tuple_only_Ad 688
#define op_count_i_rem_jId 689
#define op_count_i_return_to_trace 690
#define op_count_i_select_big_sf 691
#define op_count_i_select_float_sfI 692
#define op_count_i_select_tuple_arity_sfI 693
#define op_count_i_select_val_sfI 694
#define op_count_i_times_jId 695
#define op_count_i_trace_breakpoint 696
#define op_count_i_trim_I 697
#define op_count_i_wait_error 698
#define op_count_i_wait_error_locked 699
#define op_count_i_wait_timeout_fI 700
#define op_count_i_wait_timeout_fs 701
#define op_count_i_wait_timeout_locked_fI 702
#define op_count_i_wait_timeout_locked_fs 703
#define op_count_i_yield 704
#define op_count_if_end 705
#define op_count_init_y 706
#define op_count_init2_yy 707
#define op_count_init3_yyy 708
#define op_count_int_code_end 709
#define op_count_is_atom_fr 710
#define op_count_is_atom_fx 711
#define op_count_is_atom_fy 712
#define op_count_is_binary_fr 713
#define op_count_is_binary_fx 714
#define op_count_is_binary_fy 715
#define op_count_is_bitstring_fr 716
#define op_count_is_bitstring_fx 717
#define op_count_is_bitstring_fy 718
#define op_count_is_boolean_fr 719
#define op_count_is_boolean_fx 720
#define op_count_is_boolean_fy 721
#define op_count_is_float_fr 722
#define op_count_is_float_fx 723
#define op_count_is_float_fy 724
#define op_count_is_function_fr 725
#define op_count_is_function_fx 726
#define op_count_is_function_fy 727
#define op_count_is_function2_fss 728
#define op_count_is_integer_fr 729
#define op_count_is_integer_fx 730
#define op_count_is_integer_fy 731
#define op_count_is_integer_allocate_frII 732
#define op_count_is_integer_allocate_fxII 733
#define op_count_is_list_fr 734
#define op_count_is_list_fx 735
#define op_count_is_list_fy 736
#define op_count_is_nil_fr 737
#define op_count_is_nil_fx 738
#define op_count_is_nil_fy 739
#define op_count_is_non_empty_list_test_heap_frII 740
#define op_count_is_nonempty_list_fr 741
#define op_count_is_nonempty_list_fx 742
#define op_count_is_nonempty_list_fy 743
#define op_count_is_nonempty_list_allocate_frII 744
#define op_count_is_nonempty_list_allocate_fxII 745
#define op_count_is_number_fr 746
#define op_count_is_number_fx 747
#define op_count_is_number_fy 748
#define op_count_is_pid_fr 749
#define op_count_is_pid_fx 750
#define op_count_is_pid_fy 751
#define op_count_is_port_fr 752
#define op_count_is_port_fx 753
#define op_count_is_port_fy 754
#define op_count_is_reference_fr 755
#define op_count_is_reference_fx 756
#define op_count_is_reference_fy 757
#define op_count_is_tuple_fr 758
#define op_count_is_tuple_fx 759
#define op_count_is_tuple_fy 760
#define op_count_is_tuple_of_arity_frA 761
#define op_count_is_tuple_of_arity_fxA 762
#define op_count_is_tuple_of_arity_fyA 763
#define op_count_jump_f 764
#define op_count_label_L 765
#define op_count_loop_rec_end_f 766
#define op_count_move_nr 767
#define op_count_move_nx 768
#define op_count_move_rx 769
#define op_count_move_ry 770
#define op_count_move_xr 771
#define op_count_move_xx 772
#define op_count_move_xy 773
#define op_count_move_yr 774
#define op_count_move_yx 775
#define op_count_move_yy 776
#define op_count_move_cr 777
#define op_count_move_cx 778
#define op_count_move_cy 779
#define op_count_move_sd 780
#define op_count_move2_xyxy 781
#define op_count_move2_yxyx 782
#define op_count_move_call_xrf 783
#define op_count_move_call_yrf 784
#define op_count_move_call_last_xrfP 785
#define op_count_move_call_last_yrfP 786
#define op_count_move_call_only_xrf 787
#define op_count_move_deallocate_return_nrP 788
#define op_count_move_deallocate_return_xrP 789
#define op_count_move_deallocate_return_yrP 790
#define op_count_move_deallocate_return_crP 791
#define op_count_move_return_nr 792
#define op_count_move_return_xr 793
#define op_count_move_return_cr 794
#define op_count_node_r 795
#define op_count_node_x 796
#define op_count_node_y 797
#define op_count_normal_exit 798
#define op_count_put_n 799
#define op_count_put_r 800
#define op_count_put_x 801
#define op_count_put_y 802
#define op_count_put_c 803
#define op_count_put_list_rnx 804
#define op_count_put_list_rxr 805
#define op_count_put_list_rxx 806
#define op_count_put_list_ryx 807
#define op_count_put_list_xnx 808
#define op_count_put_list_xrr 809
#define op_count_put_list_xxr 810
#define op_count_put_list_xxx 811
#define op_count_put_list_xyx 812
#define op_count_put_list_ynx 813
#define op_count_put_list_yrr 814
#define op_count_put_list_yrx 815
#define op_count_put_list_yxx 816
#define op_count_put_list_yyr 817
#define op_count_put_list_yyx 818
#define op_count_put_list_rcr 819
#define op_count_put_list_rcx 820
#define op_count_put_list_rcy 821
#define op_count_put_list_xcr 822
#define op_count_put_list_xcx 823
#define op_count_put_list_xcy 824
#define op_count_put_list_ycr 825
#define op_count_put_list_ycx 826
#define op_count_put_list_ycy 827
#define op_count_put_list_cnr 828
#define op_count_put_list_cnx 829
#define op_count_put_list_crr 830
#define op_count_put_list_crx 831
#define op_count_put_list_cry 832
#define op_count_put_list_cxr 833
#define op_count_put_list_cxx 834
#define op_count_put_list_cxy 835
#define op_count_put_list_cyr 836
#define op_count_put_list_cyx 837
#define op_count_put_list_cyy 838
#define op_count_put_list_ssd 839
#define op_count_put_string_IId 840
#define op_count_raise_ss 841
#define op_count_remove_message 842
#define op_count_return 843
#define op_count_return_trace 844
#define op_count_self_r 845
#define op_count_self_x 846
#define op_count_self_y 847
#define op_count_send 848
#define op_count_set_tuple_element_sdP 849
#define op_count_system_limit_j 850
#define op_count_test_arity_frA 851
#define op_count_test_arity_fxA 852
#define op_count_test_arity_fyA 853
#define op_count_test_heap_II 854
#define op_count_test_heap_1_put_list_Iy 855
#define op_count_timeout 856
#define op_count_timeout_locked 857
#define op_count_too_old_compiler 858
#define op_count_try_case_end_s 859
#define op_count_try_end_y 860
#define op_count_wait_f 861
#define op_count_wait_locked_f 862
#define op_count_wait_unlocked_f 863

#define DEFINE_OPCODES \
&&lb_allocate_tt, \
&&lb_allocate_heap_III, \
&&lb_allocate_heap_zero_III, \
&&lb_allocate_init_tIy, \
&&lb_allocate_zero_tt, \
&&lb_apply_I, \
&&lb_apply_bif, \
&&lb_apply_last_IP, \
&&lb_badarg_j, \
&&lb_badmatch_s, \
&&lb_bif1_fbsd, \
&&lb_bif1_body_bsd, \
&&lb_bs_context_to_binary_r, \
&&lb_bs_context_to_binary_x, \
&&lb_bs_context_to_binary_y, \
&&lb_bs_init_writable, \
&&lb_bs_put_string_II, \
&&lb_bs_test_tail_imm2_frI, \
&&lb_bs_test_tail_imm2_fxI, \
&&lb_bs_test_unit_frI, \
&&lb_bs_test_unit_fxI, \
&&lb_bs_test_unit8_fr, \
&&lb_bs_test_unit8_fx, \
&&lb_bs_test_zero_tail2_fr, \
&&lb_bs_test_zero_tail2_fx, \
&&lb_call_bif0_e, \
&&lb_call_bif1_e, \
&&lb_call_bif2_e, \
&&lb_call_bif3_e, \
&&lb_call_error_handler, \
&&lb_call_traced_function, \
&&lb_case_end_s, \
&&lb_catch_yf, \
&&lb_catch_end_y, \
&&lb_continue_exit, \
&&lb_deallocate_I, \
&&lb_deallocate_return_P, \
&&lb_error_action_code, \
&&lb_extract_next_element_x, \
&&lb_extract_next_element_y, \
&&lb_extract_next_element2_x, \
&&lb_extract_next_element2_y, \
&&lb_extract_next_element3_x, \
&&lb_extract_next_element3_y, \
&&lb_fclearerror, \
&&lb_fconv_dl, \
&&lb_fmove_ql, \
&&lb_fmove_dl, \
&&lb_fmove_new_ld, \
&&lb_get_list_rrx, \
&&lb_get_list_rry, \
&&lb_get_list_rxr, \
&&lb_get_list_rxx, \
&&lb_get_list_rxy, \
&&lb_get_list_ryr, \
&&lb_get_list_ryx, \
&&lb_get_list_ryy, \
&&lb_get_list_xrx, \
&&lb_get_list_xry, \
&&lb_get_list_xxr, \
&&lb_get_list_xxx, \
&&lb_get_list_xxy, \
&&lb_get_list_xyr, \
&&lb_get_list_xyx, \
&&lb_get_list_xyy, \
&&lb_get_list_yrx, \
&&lb_get_list_yry, \
&&lb_get_list_yxr, \
&&lb_get_list_yxx, \
&&lb_get_list_yxy, \
&&lb_get_list_yyr, \
&&lb_get_list_yyx, \
&&lb_get_list_yyy, \
&&lb_hipe_call_count, \
&&lb_hipe_trap_call, \
&&lb_hipe_trap_call_closure, \
&&lb_hipe_trap_resume, \
&&lb_hipe_trap_return, \
&&lb_hipe_trap_throw, \
&&lb_i_apply, \
&&lb_i_apply_fun, \
&&lb_i_apply_fun_last_P, \
&&lb_i_apply_fun_only, \
&&lb_i_apply_last_P, \
&&lb_i_apply_only, \
&&lb_i_band_jId, \
&&lb_i_bif2_fbd, \
&&lb_i_bif2_body_bd, \
&&lb_i_bor_jId, \
&&lb_i_bs_add_jId, \
&&lb_i_bs_append_jIIId, \
&&lb_i_bs_bits_to_bytes_rjd, \
&&lb_i_bs_bits_to_bytes_xjd, \
&&lb_i_bs_bits_to_bytes_yjd, \
&&lb_i_bs_get_binary2_frIsId, \
&&lb_i_bs_get_binary2_fxIsId, \
&&lb_i_bs_get_binary_all2_frIId, \
&&lb_i_bs_get_binary_all2_fxIId, \
&&lb_i_bs_get_binary_all_reuse_rfI, \
&&lb_i_bs_get_binary_all_reuse_xfI, \
&&lb_i_bs_get_binary_imm2_frIIId, \
&&lb_i_bs_get_binary_imm2_fxIIId, \
&&lb_i_bs_get_float2_frIsId, \
&&lb_i_bs_get_float2_fxIsId, \
&&lb_i_bs_get_integer_fIId, \
&&lb_i_bs_get_integer_16_rfd, \
&&lb_i_bs_get_integer_16_xfd, \
&&lb_i_bs_get_integer_32_rfId, \
&&lb_i_bs_get_integer_32_xfId, \
&&lb_i_bs_get_integer_8_rfd, \
&&lb_i_bs_get_integer_8_xfd, \
&&lb_i_bs_get_integer_imm_rIIfId, \
&&lb_i_bs_get_integer_imm_xIIfId, \
&&lb_i_bs_get_integer_small_imm_rIfId, \
&&lb_i_bs_get_integer_small_imm_xIfId, \
&&lb_i_bs_get_utf16_rfId, \
&&lb_i_bs_get_utf16_xfId, \
&&lb_i_bs_get_utf8_rfd, \
&&lb_i_bs_get_utf8_xfd, \
&&lb_i_bs_init_IId, \
&&lb_i_bs_init_bits_IId, \
&&lb_i_bs_init_bits_fail_rjId, \
&&lb_i_bs_init_bits_fail_xjId, \
&&lb_i_bs_init_bits_fail_yjId, \
&&lb_i_bs_init_bits_fail_heap_IjId, \
&&lb_i_bs_init_bits_heap_IIId, \
&&lb_i_bs_init_fail_rjId, \
&&lb_i_bs_init_fail_xjId, \
&&lb_i_bs_init_fail_yjId, \
&&lb_i_bs_init_fail_heap_IjId, \
&&lb_i_bs_init_heap_IIId, \
&&lb_i_bs_init_heap_bin_IId, \
&&lb_i_bs_init_heap_bin_heap_IIId, \
&&lb_i_bs_match_string_rfII, \
&&lb_i_bs_match_string_xfII, \
&&lb_i_bs_private_append_jId, \
&&lb_i_bs_put_utf16_jIs, \
&&lb_i_bs_put_utf8_js, \
&&lb_i_bs_restore2_rI, \
&&lb_i_bs_restore2_xI, \
&&lb_i_bs_save2_rI, \
&&lb_i_bs_save2_xI, \
&&lb_i_bs_skip_bits2_frxI, \
&&lb_i_bs_skip_bits2_fryI, \
&&lb_i_bs_skip_bits2_fxrI, \
&&lb_i_bs_skip_bits2_fxxI, \
&&lb_i_bs_skip_bits2_fxyI, \
&&lb_i_bs_skip_bits_all2_frI, \
&&lb_i_bs_skip_bits_all2_fxI, \
&&lb_i_bs_skip_bits_imm2_frI, \
&&lb_i_bs_skip_bits_imm2_fxI, \
&&lb_i_bs_start_match2_rfIId, \
&&lb_i_bs_start_match2_xfIId, \
&&lb_i_bs_start_match2_yfIId, \
&&lb_i_bs_utf16_size_sd, \
&&lb_i_bs_utf8_size_sd, \
&&lb_i_bs_validate_unicode_js, \
&&lb_i_bs_validate_unicode_retract_j, \
&&lb_i_bsl_jId, \
&&lb_i_bsr_jId, \
&&lb_i_bxor_jId, \
&&lb_i_call_f, \
&&lb_i_call_ext_e, \
&&lb_i_call_ext_last_eP, \
&&lb_i_call_ext_only_e, \
&&lb_i_call_fun_I, \
&&lb_i_call_fun_last_IP, \
&&lb_i_call_last_fP, \
&&lb_i_call_only_f, \
&&lb_i_count_breakpoint, \
&&lb_i_debug_breakpoint, \
&&lb_i_element_jssd, \
&&lb_i_fadd_lll, \
&&lb_i_fast_element_jIsd, \
&&lb_i_fcheckerror, \
&&lb_i_fdiv_lll, \
&&lb_i_fetch_rx, \
&&lb_i_fetch_ry, \
&&lb_i_fetch_xr, \
&&lb_i_fetch_xx, \
&&lb_i_fetch_xy, \
&&lb_i_fetch_yr, \
&&lb_i_fetch_yx, \
&&lb_i_fetch_yy, \
&&lb_i_fetch_rc, \
&&lb_i_fetch_xc, \
&&lb_i_fetch_yc, \
&&lb_i_fetch_cr, \
&&lb_i_fetch_cx, \
&&lb_i_fetch_cy, \
&&lb_i_fetch_cc, \
&&lb_i_fetch_ss, \
&&lb_i_fmul_lll, \
&&lb_i_fnegate_ll, \
&&lb_i_fsub_lll, \
&&lb_i_func_info_IaaI, \
&&lb_i_gc_bif1_jIsId, \
&&lb_i_get_sd, \
&&lb_i_get_tuple_element_rPr, \
&&lb_i_get_tuple_element_rPx, \
&&lb_i_get_tuple_element_rPy, \
&&lb_i_get_tuple_element_xPr, \
&&lb_i_get_tuple_element_xPx, \
&&lb_i_get_tuple_element_xPy, \
&&lb_i_get_tuple_element_yPr, \
&&lb_i_get_tuple_element_yPx, \
&&lb_i_get_tuple_element_yPy, \
&&lb_i_global_cons, \
&&lb_i_global_copy, \
&&lb_i_global_tuple, \
&&lb_i_hibernate, \
&&lb_i_int_bnot_jsId, \
&&lb_i_int_div_jId, \
&&lb_i_is_eq_f, \
&&lb_i_is_eq_exact_f, \
&&lb_i_is_eq_immed_frc, \
&&lb_i_is_eq_immed_fxc, \
&&lb_i_is_eq_immed_fyc, \
&&lb_i_is_ge_f, \
&&lb_i_is_lt_f, \
&&lb_i_is_ne_f, \
&&lb_i_is_ne_exact_f, \
&&lb_i_jump_on_val_sfII, \
&&lb_i_jump_on_val_zero_sfI, \
&&lb_i_loop_rec_fr, \
&&lb_i_m_div_jId, \
&&lb_i_make_fun_It, \
&&lb_i_minus_jId, \
&&lb_i_move_call_crf, \
&&lb_i_move_call_ext_cre, \
&&lb_i_move_call_ext_last_ePcr, \
&&lb_i_move_call_ext_only_ecr, \
&&lb_i_move_call_last_fPcr, \
&&lb_i_move_call_only_fcr, \
&&lb_i_mtrace_breakpoint, \
&&lb_i_new_bs_put_binary_jsIs, \
&&lb_i_new_bs_put_binary_all_jsI, \
&&lb_i_new_bs_put_binary_imm_jIs, \
&&lb_i_new_bs_put_float_jsIs, \
&&lb_i_new_bs_put_float_imm_jIIs, \
&&lb_i_new_bs_put_integer_jsIs, \
&&lb_i_new_bs_put_integer_imm_jIIs, \
&&lb_i_plus_jId, \
&&lb_i_put_tuple_Anr, \
&&lb_i_put_tuple_Anx, \
&&lb_i_put_tuple_Arx, \
&&lb_i_put_tuple_Ary, \
&&lb_i_put_tuple_Axr, \
&&lb_i_put_tuple_Axx, \
&&lb_i_put_tuple_Axy, \
&&lb_i_put_tuple_Ayr, \
&&lb_i_put_tuple_Ayx, \
&&lb_i_put_tuple_Ayy, \
&&lb_i_put_tuple_Acr, \
&&lb_i_put_tuple_Acx, \
&&lb_i_put_tuple_Acy, \
&&lb_i_put_tuple_only_Ad, \
&&lb_i_rem_jId, \
&&lb_i_return_to_trace, \
&&lb_i_select_big_sf, \
&&lb_i_select_float_sfI, \
&&lb_i_select_tuple_arity_sfI, \
&&lb_i_select_val_sfI, \
&&lb_i_times_jId, \
&&lb_i_trace_breakpoint, \
&&lb_i_trim_I, \
&&lb_i_wait_error, \
&&lb_i_wait_error_locked, \
&&lb_i_wait_timeout_fI, \
&&lb_i_wait_timeout_fs, \
&&lb_i_wait_timeout_locked_fI, \
&&lb_i_wait_timeout_locked_fs, \
&&lb_i_yield, \
&&lb_if_end, \
&&lb_init_y, \
&&lb_init2_yy, \
&&lb_init3_yyy, \
&&lb_int_code_end, \
&&lb_is_atom_fr, \
&&lb_is_atom_fx, \
&&lb_is_atom_fy, \
&&lb_is_binary_fr, \
&&lb_is_binary_fx, \
&&lb_is_binary_fy, \
&&lb_is_bitstring_fr, \
&&lb_is_bitstring_fx, \
&&lb_is_bitstring_fy, \
&&lb_is_boolean_fr, \
&&lb_is_boolean_fx, \
&&lb_is_boolean_fy, \
&&lb_is_float_fr, \
&&lb_is_float_fx, \
&&lb_is_float_fy, \
&&lb_is_function_fr, \
&&lb_is_function_fx, \
&&lb_is_function_fy, \
&&lb_is_function2_fss, \
&&lb_is_integer_fr, \
&&lb_is_integer_fx, \
&&lb_is_integer_fy, \
&&lb_is_integer_allocate_frII, \
&&lb_is_integer_allocate_fxII, \
&&lb_is_list_fr, \
&&lb_is_list_fx, \
&&lb_is_list_fy, \
&&lb_is_nil_fr, \
&&lb_is_nil_fx, \
&&lb_is_nil_fy, \
&&lb_is_non_empty_list_test_heap_frII, \
&&lb_is_nonempty_list_fr, \
&&lb_is_nonempty_list_fx, \
&&lb_is_nonempty_list_fy, \
&&lb_is_nonempty_list_allocate_frII, \
&&lb_is_nonempty_list_allocate_fxII, \
&&lb_is_number_fr, \
&&lb_is_number_fx, \
&&lb_is_number_fy, \
&&lb_is_pid_fr, \
&&lb_is_pid_fx, \
&&lb_is_pid_fy, \
&&lb_is_port_fr, \
&&lb_is_port_fx, \
&&lb_is_port_fy, \
&&lb_is_reference_fr, \
&&lb_is_reference_fx, \
&&lb_is_reference_fy, \
&&lb_is_tuple_fr, \
&&lb_is_tuple_fx, \
&&lb_is_tuple_fy, \
&&lb_is_tuple_of_arity_frA, \
&&lb_is_tuple_of_arity_fxA, \
&&lb_is_tuple_of_arity_fyA, \
&&lb_jump_f, \
&&lb_label_L, \
&&lb_loop_rec_end_f, \
&&lb_move_nr, \
&&lb_move_nx, \
&&lb_move_rx, \
&&lb_move_ry, \
&&lb_move_xr, \
&&lb_move_xx, \
&&lb_move_xy, \
&&lb_move_yr, \
&&lb_move_yx, \
&&lb_move_yy, \
&&lb_move_cr, \
&&lb_move_cx, \
&&lb_move_cy, \
&&lb_move_sd, \
&&lb_move2_xyxy, \
&&lb_move2_yxyx, \
&&lb_move_call_xrf, \
&&lb_move_call_yrf, \
&&lb_move_call_last_xrfP, \
&&lb_move_call_last_yrfP, \
&&lb_move_call_only_xrf, \
&&lb_move_deallocate_return_nrP, \
&&lb_move_deallocate_return_xrP, \
&&lb_move_deallocate_return_yrP, \
&&lb_move_deallocate_return_crP, \
&&lb_move_return_nr, \
&&lb_move_return_xr, \
&&lb_move_return_cr, \
&&lb_node_r, \
&&lb_node_x, \
&&lb_node_y, \
&&lb_normal_exit, \
&&lb_put_n, \
&&lb_put_r, \
&&lb_put_x, \
&&lb_put_y, \
&&lb_put_c, \
&&lb_put_list_rnx, \
&&lb_put_list_rxr, \
&&lb_put_list_rxx, \
&&lb_put_list_ryx, \
&&lb_put_list_xnx, \
&&lb_put_list_xrr, \
&&lb_put_list_xxr, \
&&lb_put_list_xxx, \
&&lb_put_list_xyx, \
&&lb_put_list_ynx, \
&&lb_put_list_yrr, \
&&lb_put_list_yrx, \
&&lb_put_list_yxx, \
&&lb_put_list_yyr, \
&&lb_put_list_yyx, \
&&lb_put_list_rcr, \
&&lb_put_list_rcx, \
&&lb_put_list_rcy, \
&&lb_put_list_xcr, \
&&lb_put_list_xcx, \
&&lb_put_list_xcy, \
&&lb_put_list_ycr, \
&&lb_put_list_ycx, \
&&lb_put_list_ycy, \
&&lb_put_list_cnr, \
&&lb_put_list_cnx, \
&&lb_put_list_crr, \
&&lb_put_list_crx, \
&&lb_put_list_cry, \
&&lb_put_list_cxr, \
&&lb_put_list_cxx, \
&&lb_put_list_cxy, \
&&lb_put_list_cyr, \
&&lb_put_list_cyx, \
&&lb_put_list_cyy, \
&&lb_put_list_ssd, \
&&lb_put_string_IId, \
&&lb_raise_ss, \
&&lb_remove_message, \
&&lb_return, \
&&lb_return_trace, \
&&lb_self_r, \
&&lb_self_x, \
&&lb_self_y, \
&&lb_send, \
&&lb_set_tuple_element_sdP, \
&&lb_system_limit_j, \
&&lb_test_arity_frA, \
&&lb_test_arity_fxA, \
&&lb_test_arity_fyA, \
&&lb_test_heap_II, \
&&lb_test_heap_1_put_list_Iy, \
&&lb_timeout, \
&&lb_timeout_locked, \
&&lb_too_old_compiler, \
&&lb_try_case_end_s, \
&&lb_try_end_y, \
&&lb_wait_f, \
&&lb_wait_locked_f, \
&&lb_wait_unlocked_f,

#define DEFINE_COUNTING_OPCODES \
&&lb_count_allocate_tt, \
&&lb_count_allocate_heap_III, \
&&lb_count_allocate_heap_zero_III, \
&&lb_count_allocate_init_tIy, \
&&lb_count_allocate_zero_tt, \
&&lb_count_apply_I, \
&&lb_count_apply_bif, \
&&lb_count_apply_last_IP, \
&&lb_count_badarg_j, \
&&lb_count_badmatch_s, \
&&lb_count_bif1_fbsd, \
&&lb_count_bif1_body_bsd, \
&&lb_count_bs_context_to_binary_r, \
&&lb_count_bs_context_to_binary_x, \
&&lb_count_bs_context_to_binary_y, \
&&lb_count_bs_init_writable, \
&&lb_count_bs_put_string_II, \
&&lb_count_bs_test_tail_imm2_frI, \
&&lb_count_bs_test_tail_imm2_fxI, \
&&lb_count_bs_test_unit_frI, \
&&lb_count_bs_test_unit_fxI, \
&&lb_count_bs_test_unit8_fr, \
&&lb_count_bs_test_unit8_fx, \
&&lb_count_bs_test_zero_tail2_fr, \
&&lb_count_bs_test_zero_tail2_fx, \
&&lb_count_call_bif0_e, \
&&lb_count_call_bif1_e, \
&&lb_count_call_bif2_e, \
&&lb_count_call_bif3_e, \
&&lb_count_call_error_handler, \
&&lb_count_call_traced_function, \
&&lb_count_case_end_s, \
&&lb_count_catch_yf, \
&&lb_count_catch_end_y, \
&&lb_count_continue_exit, \
&&lb_count_deallocate_I, \
&&lb_count_deallocate_return_P, \
&&lb_count_error_action_code, \
&&lb_count_extract_next_element_x, \
&&lb_count_extract_next_element_y, \
&&lb_count_extract_next_element2_x, \
&&lb_count_extract_next_element2_y, \
&&lb_count_extract_next_element3_x, \
&&lb_count_extract_next_element3_y, \
&&lb_count_fclearerror, \
&&lb_count_fconv_dl, \
&&lb_count_fmove_ql, \
&&lb_count_fmove_dl, \
&&lb_count_fmove_new_ld, \
&&lb_count_get_list_rrx, \
&&lb_count_get_list_rry, \
&&lb_count_get_list_rxr, \
&&lb_count_get_list_rxx, \
&&lb_count_get_list_rxy, \
&&lb_count_get_list_ryr, \
&&lb_count_get_list_ryx, \
&&lb_count_get_list_ryy, \
&&lb_count_get_list_xrx, \
&&lb_count_get_list_xry, \
&&lb_count_get_list_xxr, \
&&lb_count_get_list_xxx, \
&&lb_count_get_list_xxy, \
&&lb_count_get_list_xyr, \
&&lb_count_get_list_xyx, \
&&lb_count_get_list_xyy, \
&&lb_count_get_list_yrx, \
&&lb_count_get_list_yry, \
&&lb_count_get_list_yxr, \
&&lb_count_get_list_yxx, \
&&lb_count_get_list_yxy, \
&&lb_count_get_list_yyr, \
&&lb_count_get_list_yyx, \
&&lb_count_get_list_yyy, \
&&lb_count_hipe_call_count, \
&&lb_count_hipe_trap_call, \
&&lb_count_hipe_trap_call_closure, \
&&lb_count_hipe_trap_resume, \
&&lb_count_hipe_trap_return, \
&&lb_count_hipe_trap_throw, \
&&lb_count_i_apply, \
&&lb_count_i_apply_fun, \
&&lb_count_i_apply_fun_last_P, \
&&lb_count_i_apply_fun_only, \
&&lb_count_i_apply_last_P, \
&&lb_count_i_apply_only, \
&&lb_count_i_band_jId, \
&&lb_count_i_bif2_fbd, \
&&lb_count_i_bif2_body_bd, \
&&lb_count_i_bor_jId, \
&&lb_count_i_bs_add_jId, \
&&lb_count_i_bs_append_jIIId, \
&&lb_count_i_bs_bits_to_bytes_rjd, \
&&lb_count_i_bs_bits_to_bytes_xjd, \
&&lb_count_i_bs_bits_to_bytes_yjd, \
&&lb_count_i_bs_get_binary2_frIsId, \
&&lb_count_i_bs_get_binary2_fxIsId, \
&&lb_count_i_bs_get_binary_all2_frIId, \
&&lb_count_i_bs_get_binary_all2_fxIId, \
&&lb_count_i_bs_get_binary_all_reuse_rfI, \
&&lb_count_i_bs_get_binary_all_reuse_xfI, \
&&lb_count_i_bs_get_binary_imm2_frIIId, \
&&lb_count_i_bs_get_binary_imm2_fxIIId, \
&&lb_count_i_bs_get_float2_frIsId, \
&&lb_count_i_bs_get_float2_fxIsId, \
&&lb_count_i_bs_get_integer_fIId, \
&&lb_count_i_bs_get_integer_16_rfd, \
&&lb_count_i_bs_get_integer_16_xfd, \
&&lb_count_i_bs_get_integer_32_rfId, \
&&lb_count_i_bs_get_integer_32_xfId, \
&&lb_count_i_bs_get_integer_8_rfd, \
&&lb_count_i_bs_get_integer_8_xfd, \
&&lb_count_i_bs_get_integer_imm_rIIfId, \
&&lb_count_i_bs_get_integer_imm_xIIfId, \
&&lb_count_i_bs_get_integer_small_imm_rIfId, \
&&lb_count_i_bs_get_integer_small_imm_xIfId, \
&&lb_count_i_bs_get_utf16_rfId, \
&&lb_count_i_bs_get_utf16_xfId, \
&&lb_count_i_bs_get_utf8_rfd, \
&&lb_count_i_bs_get_utf8_xfd, \
&&lb_count_i_bs_init_IId, \
&&lb_count_i_bs_init_bits_IId, \
&&lb_count_i_bs_init_bits_fail_rjId, \
&&lb_count_i_bs_init_bits_fail_xjId, \
&&lb_count_i_bs_init_bits_fail_yjId, \
&&lb_count_i_bs_init_bits_fail_heap_IjId, \
&&lb_count_i_bs_init_bits_heap_IIId, \
&&lb_count_i_bs_init_fail_rjId, \
&&lb_count_i_bs_init_fail_xjId, \
&&lb_count_i_bs_init_fail_yjId, \
&&lb_count_i_bs_init_fail_heap_IjId, \
&&lb_count_i_bs_init_heap_IIId, \
&&lb_count_i_bs_init_heap_bin_IId, \
&&lb_count_i_bs_init_heap_bin_heap_IIId, \
&&lb_count_i_bs_match_string_rfII, \
&&lb_count_i_bs_match_string_xfII, \
&&lb_count_i_bs_private_append_jId, \
&&lb_count_i_bs_put_utf16_jIs, \
&&lb_count_i_bs_put_utf8_js, \
&&lb_count_i_bs_restore2_rI, \
&&lb_count_i_bs_restore2_xI, \
&&lb_count_i_bs_save2_rI, \
&&lb_count_i_bs_save2_xI, \
&&lb_count_i_bs_skip_bits2_frxI, \
&&lb_count_i_bs_skip_bits2_fryI, \
&&lb_count_i_bs_skip_bits2_fxrI, \
&&lb_count_i_bs_skip_bits2_fxxI, \
&&lb_count_i_bs_skip_bits2_fxyI, \
&&lb_count_i_bs_skip_bits_all2_frI, \
&&lb_count_i_bs_skip_bits_all2_fxI, \
&&lb_count_i_bs_skip_bits_imm2_frI, \
&&lb_count_i_bs_skip_bits_imm2_fxI, \
&&lb_count_i_bs_start_match2_rfIId, \
&&lb_count_i_bs_start_match2_xfIId, \
&&lb_count_i_bs_start_match2_yfIId, \
&&lb_count_i_bs_utf16_size_sd, \
&&lb_count_i_bs_utf8_size_sd, \
&&lb_count_i_bs_validate_unicode_js, \
&&lb_count_i_bs_validate_unicode_retract_j, \
&&lb_count_i_bsl_jId, \
&&lb_count_i_bsr_jId, \
&&lb_count_i_bxor_jId, \
&&lb_count_i_call_f, \
&&lb_count_i_call_ext_e, \
&&lb_count_i_call_ext_last_eP, \
&&lb_count_i_call_ext_only_e, \
&&lb_count_i_call_fun_I, \
&&lb_count_i_call_fun_last_IP, \
&&lb_count_i_call_last_fP, \
&&lb_count_i_call_only_f, \
&&lb_count_i_count_breakpoint, \
&&lb_count_i_debug_breakpoint, \
&&lb_count_i_element_jssd, \
&&lb_count_i_fadd_lll, \
&&lb_count_i_fast_element_jIsd, \
&&lb_count_i_fcheckerror, \
&&lb_count_i_fdiv_lll, \
&&lb_count_i_fetch_rx, \
&&lb_count_i_fetch_ry, \
&&lb_count_i_fetch_xr, \
&&lb_count_i_fetch_xx, \
&&lb_count_i_fetch_xy, \
&&lb_count_i_fetch_yr, \
&&lb_count_i_fetch_yx, \
&&lb_count_i_fetch_yy, \
&&lb_count_i_fetch_rc, \
&&lb_count_i_fetch_xc, \
&&lb_count_i_fetch_yc, \
&&lb_count_i_fetch_cr, \
&&lb_count_i_fetch_cx, \
&&lb_count_i_fetch_cy, \
&&lb_count_i_fetch_cc, \
&&lb_count_i_fetch_ss, \
&&lb_count_i_fmul_lll, \
&&lb_count_i_fnegate_ll, \
&&lb_count_i_fsub_lll, \
&&lb_count_i_func_info_IaaI, \
&&lb_count_i_gc_bif1_jIsId, \
&&lb_count_i_get_sd, \
&&lb_count_i_get_tuple_element_rPr, \
&&lb_count_i_get_tuple_element_rPx, \
&&lb_count_i_get_tuple_element_rPy, \
&&lb_count_i_get_tuple_element_xPr, \
&&lb_count_i_get_tuple_element_xPx, \
&&lb_count_i_get_tuple_element_xPy, \
&&lb_count_i_get_tuple_element_yPr, \
&&lb_count_i_get_tuple_element_yPx, \
&&lb_count_i_get_tuple_element_yPy, \
&&lb_count_i_global_cons, \
&&lb_count_i_global_copy, \
&&lb_count_i_global_tuple, \
&&lb_count_i_hibernate, \
&&lb_count_i_int_bnot_jsId, \
&&lb_count_i_int_div_jId, \
&&lb_count_i_is_eq_f, \
&&lb_count_i_is_eq_exact_f, \
&&lb_count_i_is_eq_immed_frc, \
&&lb_count_i_is_eq_immed_fxc, \
&&lb_count_i_is_eq_immed_fyc, \
&&lb_count_i_is_ge_f, \
&&lb_count_i_is_lt_f, \
&&lb_count_i_is_ne_f, \
&&lb_count_i_is_ne_exact_f, \
&&lb_count_i_jump_on_val_sfII, \
&&lb_count_i_jump_on_val_zero_sfI, \
&&lb_count_i_loop_rec_fr, \
&&lb_count_i_m_div_jId, \
&&lb_count_i_make_fun_It, \
&&lb_count_i_minus_jId, \
&&lb_count_i_move_call_crf, \
&&lb_count_i_move_call_ext_cre, \
&&lb_count_i_move_call_ext_last_ePcr, \
&&lb_count_i_move_call_ext_only_ecr, \
&&lb_count_i_move_call_last_fPcr, \
&&lb_count_i_move_call_only_fcr, \
&&lb_count_i_mtrace_breakpoint, \
&&lb_count_i_new_bs_put_binary_jsIs, \
&&lb_count_i_new_bs_put_binary_all_jsI, \
&&lb_count_i_new_bs_put_binary_imm_jIs, \
&&lb_count_i_new_bs_put_float_jsIs, \
&&lb_count_i_new_bs_put_float_imm_jIIs, \
&&lb_count_i_new_bs_put_integer_jsIs, \
&&lb_count_i_new_bs_put_integer_imm_jIIs, \
&&lb_count_i_plus_jId, \
&&lb_count_i_put_tuple_Anr, \
&&lb_count_i_put_tuple_Anx, \
&&lb_count_i_put_tuple_Arx, \
&&lb_count_i_put_tuple_Ary, \
&&lb_count_i_put_tuple_Axr, \
&&lb_count_i_put_tuple_Axx, \
&&lb_count_i_put_tuple_Axy, \
&&lb_count_i_put_tuple_Ayr, \
&&lb_count_i_put_tuple_Ayx, \
&&lb_count_i_put_tuple_Ayy, \
&&lb_count_i_put_tuple_Acr, \
&&lb_count_i_put_tuple_Acx, \
&&lb_count_i_put_tuple_Acy, \
&&lb_count_i_put_tuple_only_Ad, \
&&lb_count_i_rem_jId, \
&&lb_count_i_return_to_trace, \
&&lb_count_i_select_big_sf, \
&&lb_count_i_select_float_sfI, \
&&lb_count_i_select_tuple_arity_sfI, \
&&lb_count_i_select_val_sfI, \
&&lb_count_i_times_jId, \
&&lb_count_i_trace_breakpoint, \
&&lb_count_i_trim_I, \
&&lb_count_i_wait_error, \
&&lb_count_i_wait_error_locked, \
&&lb_count_i_wait_timeout_fI, \
&&lb_count_i_wait_timeout_fs, \
&&lb_count_i_wait_timeout_locked_fI, \
&&lb_count_i_wait_timeout_locked_fs, \
&&lb_count_i_yield, \
&&lb_count_if_end, \
&&lb_count_init_y, \
&&lb_count_init2_yy, \
&&lb_count_init3_yyy, \
&&lb_count_int_code_end, \
&&lb_count_is_atom_fr, \
&&lb_count_is_atom_fx, \
&&lb_count_is_atom_fy, \
&&lb_count_is_binary_fr, \
&&lb_count_is_binary_fx, \
&&lb_count_is_binary_fy, \
&&lb_count_is_bitstring_fr, \
&&lb_count_is_bitstring_fx, \
&&lb_count_is_bitstring_fy, \
&&lb_count_is_boolean_fr, \
&&lb_count_is_boolean_fx, \
&&lb_count_is_boolean_fy, \
&&lb_count_is_float_fr, \
&&lb_count_is_float_fx, \
&&lb_count_is_float_fy, \
&&lb_count_is_function_fr, \
&&lb_count_is_function_fx, \
&&lb_count_is_function_fy, \
&&lb_count_is_function2_fss, \
&&lb_count_is_integer_fr, \
&&lb_count_is_integer_fx, \
&&lb_count_is_integer_fy, \
&&lb_count_is_integer_allocate_frII, \
&&lb_count_is_integer_allocate_fxII, \
&&lb_count_is_list_fr, \
&&lb_count_is_list_fx, \
&&lb_count_is_list_fy, \
&&lb_count_is_nil_fr, \
&&lb_count_is_nil_fx, \
&&lb_count_is_nil_fy, \
&&lb_count_is_non_empty_list_test_heap_frII, \
&&lb_count_is_nonempty_list_fr, \
&&lb_count_is_nonempty_list_fx, \
&&lb_count_is_nonempty_list_fy, \
&&lb_count_is_nonempty_list_allocate_frII, \
&&lb_count_is_nonempty_list_allocate_fxII, \
&&lb_count_is_number_fr, \
&&lb_count_is_number_fx, \
&&lb_count_is_number_fy, \
&&lb_count_is_pid_fr, \
&&lb_count_is_pid_fx, \
&&lb_count_is_pid_fy, \
&&lb_count_is_port_fr, \
&&lb_count_is_port_fx, \
&&lb_count_is_port_fy, \
&&lb_count_is_reference_fr, \
&&lb_count_is_reference_fx, \
&&lb_count_is_reference_fy, \
&&lb_count_is_tuple_fr, \
&&lb_count_is_tuple_fx, \
&&lb_count_is_tuple_fy, \
&&lb_count_is_tuple_of_arity_frA, \
&&lb_count_is_tuple_of_arity_fxA, \
&&lb_count_is_tuple_of_arity_fyA, \
&&lb_count_jump_f, \
&&lb_count_label_L, \
&&lb_count_loop_rec_end_f, \
&&lb_count_move_nr, \
&&lb_count_move_nx, \
&&lb_count_move_rx, \
&&lb_count_move_ry, \
&&lb_count_move_xr, \
&&lb_count_move_xx, \
&&lb_count_move_xy, \
&&lb_count_move_yr, \
&&lb_count_move_yx, \
&&lb_count_move_yy, \
&&lb_count_move_cr, \
&&lb_count_move_cx, \
&&lb_count_move_cy, \
&&lb_count_move_sd, \
&&lb_count_move2_xyxy, \
&&lb_count_move2_yxyx, \
&&lb_count_move_call_xrf, \
&&lb_count_move_call_yrf, \
&&lb_count_move_call_last_xrfP, \
&&lb_count_move_call_last_yrfP, \
&&lb_count_move_call_only_xrf, \
&&lb_count_move_deallocate_return_nrP, \
&&lb_count_move_deallocate_return_xrP, \
&&lb_count_move_deallocate_return_yrP, \
&&lb_count_move_deallocate_return_crP, \
&&lb_count_move_return_nr, \
&&lb_count_move_return_xr, \
&&lb_count_move_return_cr, \
&&lb_count_node_r, \
&&lb_count_node_x, \
&&lb_count_node_y, \
&&lb_count_normal_exit, \
&&lb_count_put_n, \
&&lb_count_put_r, \
&&lb_count_put_x, \
&&lb_count_put_y, \
&&lb_count_put_c, \
&&lb_count_put_list_rnx, \
&&lb_count_put_list_rxr, \
&&lb_count_put_list_rxx, \
&&lb_count_put_list_ryx, \
&&lb_count_put_list_xnx, \
&&lb_count_put_list_xrr, \
&&lb_count_put_list_xxr, \
&&lb_count_put_list_xxx, \
&&lb_count_put_list_xyx, \
&&lb_count_put_list_ynx, \
&&lb_count_put_list_yrr, \
&&lb_count_put_list_yrx, \
&&lb_count_put_list_yxx, \
&&lb_count_put_list_yyr, \
&&lb_count_put_list_yyx, \
&&lb_count_put_list_rcr, \
&&lb_count_put_list_rcx, \
&&lb_count_put_list_rcy, \
&&lb_count_put_list_xcr, \
&&lb_count_put_list_xcx, \
&&lb_count_put_list_xcy, \
&&lb_count_put_list_ycr, \
&&lb_count_put_list_ycx, \
&&lb_count_put_list_ycy, \
&&lb_count_put_list_cnr, \
&&lb_count_put_list_cnx, \
&&lb_count_put_list_crr, \
&&lb_count_put_list_crx, \
&&lb_count_put_list_cry, \
&&lb_count_put_list_cxr, \
&&lb_count_put_list_cxx, \
&&lb_count_put_list_cxy, \
&&lb_count_put_list_cyr, \
&&lb_count_put_list_cyx, \
&&lb_count_put_list_cyy, \
&&lb_count_put_list_ssd, \
&&lb_count_put_string_IId, \
&&lb_count_raise_ss, \
&&lb_count_remove_message, \
&&lb_count_return, \
&&lb_count_return_trace, \
&&lb_count_self_r, \
&&lb_count_self_x, \
&&lb_count_self_y, \
&&lb_count_send, \
&&lb_count_set_tuple_element_sdP, \
&&lb_count_system_limit_j, \
&&lb_count_test_arity_frA, \
&&lb_count_test_arity_fxA, \
&&lb_count_test_arity_fyA, \
&&lb_count_test_heap_II, \
&&lb_count_test_heap_1_put_list_Iy, \
&&lb_count_timeout, \
&&lb_count_timeout_locked, \
&&lb_count_too_old_compiler, \
&&lb_count_try_case_end_s, \
&&lb_count_try_end_y, \
&&lb_count_wait_f, \
&&lb_count_wait_locked_f, \
&&lb_count_wait_unlocked_f,

#define DEFINE_COUNTING_LABELS \
CountCase(allocate_tt): opc[0].count++; goto lb_allocate_tt; \
CountCase(allocate_heap_III): opc[1].count++; goto lb_allocate_heap_III; \
CountCase(allocate_heap_zero_III): opc[2].count++; goto lb_allocate_heap_zero_III; \
CountCase(allocate_init_tIy): opc[3].count++; goto lb_allocate_init_tIy; \
CountCase(allocate_zero_tt): opc[4].count++; goto lb_allocate_zero_tt; \
CountCase(apply_I): opc[5].count++; goto lb_apply_I; \
CountCase(apply_bif): opc[6].count++; goto lb_apply_bif; \
CountCase(apply_last_IP): opc[7].count++; goto lb_apply_last_IP; \
CountCase(badarg_j): opc[8].count++; goto lb_badarg_j; \
CountCase(badmatch_s): opc[9].count++; goto lb_badmatch_s; \
CountCase(bif1_fbsd): opc[10].count++; goto lb_bif1_fbsd; \
CountCase(bif1_body_bsd): opc[11].count++; goto lb_bif1_body_bsd; \
CountCase(bs_context_to_binary_r): opc[12].count++; goto lb_bs_context_to_binary_r; \
CountCase(bs_context_to_binary_x): opc[13].count++; goto lb_bs_context_to_binary_x; \
CountCase(bs_context_to_binary_y): opc[14].count++; goto lb_bs_context_to_binary_y; \
CountCase(bs_init_writable): opc[15].count++; goto lb_bs_init_writable; \
CountCase(bs_put_string_II): opc[16].count++; goto lb_bs_put_string_II; \
CountCase(bs_test_tail_imm2_frI): opc[17].count++; goto lb_bs_test_tail_imm2_frI; \
CountCase(bs_test_tail_imm2_fxI): opc[18].count++; goto lb_bs_test_tail_imm2_fxI; \
CountCase(bs_test_unit_frI): opc[19].count++; goto lb_bs_test_unit_frI; \
CountCase(bs_test_unit_fxI): opc[20].count++; goto lb_bs_test_unit_fxI; \
CountCase(bs_test_unit8_fr): opc[21].count++; goto lb_bs_test_unit8_fr; \
CountCase(bs_test_unit8_fx): opc[22].count++; goto lb_bs_test_unit8_fx; \
CountCase(bs_test_zero_tail2_fr): opc[23].count++; goto lb_bs_test_zero_tail2_fr; \
CountCase(bs_test_zero_tail2_fx): opc[24].count++; goto lb_bs_test_zero_tail2_fx; \
CountCase(call_bif0_e): opc[25].count++; goto lb_call_bif0_e; \
CountCase(call_bif1_e): opc[26].count++; goto lb_call_bif1_e; \
CountCase(call_bif2_e): opc[27].count++; goto lb_call_bif2_e; \
CountCase(call_bif3_e): opc[28].count++; goto lb_call_bif3_e; \
CountCase(call_error_handler): opc[29].count++; goto lb_call_error_handler; \
CountCase(call_traced_function): opc[30].count++; goto lb_call_traced_function; \
CountCase(case_end_s): opc[31].count++; goto lb_case_end_s; \
CountCase(catch_yf): opc[32].count++; goto lb_catch_yf; \
CountCase(catch_end_y): opc[33].count++; goto lb_catch_end_y; \
CountCase(continue_exit): opc[34].count++; goto lb_continue_exit; \
CountCase(deallocate_I): opc[35].count++; goto lb_deallocate_I; \
CountCase(deallocate_return_P): opc[36].count++; goto lb_deallocate_return_P; \
CountCase(error_action_code): opc[37].count++; goto lb_error_action_code; \
CountCase(extract_next_element_x): opc[38].count++; goto lb_extract_next_element_x; \
CountCase(extract_next_element_y): opc[39].count++; goto lb_extract_next_element_y; \
CountCase(extract_next_element2_x): opc[40].count++; goto lb_extract_next_element2_x; \
CountCase(extract_next_element2_y): opc[41].count++; goto lb_extract_next_element2_y; \
CountCase(extract_next_element3_x): opc[42].count++; goto lb_extract_next_element3_x; \
CountCase(extract_next_element3_y): opc[43].count++; goto lb_extract_next_element3_y; \
CountCase(fclearerror): opc[44].count++; goto lb_fclearerror; \
CountCase(fconv_dl): opc[45].count++; goto lb_fconv_dl; \
CountCase(fmove_ql): opc[46].count++; goto lb_fmove_ql; \
CountCase(fmove_dl): opc[47].count++; goto lb_fmove_dl; \
CountCase(fmove_new_ld): opc[48].count++; goto lb_fmove_new_ld; \
CountCase(get_list_rrx): opc[49].count++; goto lb_get_list_rrx; \
CountCase(get_list_rry): opc[50].count++; goto lb_get_list_rry; \
CountCase(get_list_rxr): opc[51].count++; goto lb_get_list_rxr; \
CountCase(get_list_rxx): opc[52].count++; goto lb_get_list_rxx; \
CountCase(get_list_rxy): opc[53].count++; goto lb_get_list_rxy; \
CountCase(get_list_ryr): opc[54].count++; goto lb_get_list_ryr; \
CountCase(get_list_ryx): opc[55].count++; goto lb_get_list_ryx; \
CountCase(get_list_ryy): opc[56].count++; goto lb_get_list_ryy; \
CountCase(get_list_xrx): opc[57].count++; goto lb_get_list_xrx; \
CountCase(get_list_xry): opc[58].count++; goto lb_get_list_xry; \
CountCase(get_list_xxr): opc[59].count++; goto lb_get_list_xxr; \
CountCase(get_list_xxx): opc[60].count++; goto lb_get_list_xxx; \
CountCase(get_list_xxy): opc[61].count++; goto lb_get_list_xxy; \
CountCase(get_list_xyr): opc[62].count++; goto lb_get_list_xyr; \
CountCase(get_list_xyx): opc[63].count++; goto lb_get_list_xyx; \
CountCase(get_list_xyy): opc[64].count++; goto lb_get_list_xyy; \
CountCase(get_list_yrx): opc[65].count++; goto lb_get_list_yrx; \
CountCase(get_list_yry): opc[66].count++; goto lb_get_list_yry; \
CountCase(get_list_yxr): opc[67].count++; goto lb_get_list_yxr; \
CountCase(get_list_yxx): opc[68].count++; goto lb_get_list_yxx; \
CountCase(get_list_yxy): opc[69].count++; goto lb_get_list_yxy; \
CountCase(get_list_yyr): opc[70].count++; goto lb_get_list_yyr; \
CountCase(get_list_yyx): opc[71].count++; goto lb_get_list_yyx; \
CountCase(get_list_yyy): opc[72].count++; goto lb_get_list_yyy; \
CountCase(hipe_call_count): opc[73].count++; goto lb_hipe_call_count; \
CountCase(hipe_trap_call): opc[74].count++; goto lb_hipe_trap_call; \
CountCase(hipe_trap_call_closure): opc[75].count++; goto lb_hipe_trap_call_closure; \
CountCase(hipe_trap_resume): opc[76].count++; goto lb_hipe_trap_resume; \
CountCase(hipe_trap_return): opc[77].count++; goto lb_hipe_trap_return; \
CountCase(hipe_trap_throw): opc[78].count++; goto lb_hipe_trap_throw; \
CountCase(i_apply): opc[79].count++; goto lb_i_apply; \
CountCase(i_apply_fun): opc[80].count++; goto lb_i_apply_fun; \
CountCase(i_apply_fun_last_P): opc[81].count++; goto lb_i_apply_fun_last_P; \
CountCase(i_apply_fun_only): opc[82].count++; goto lb_i_apply_fun_only; \
CountCase(i_apply_last_P): opc[83].count++; goto lb_i_apply_last_P; \
CountCase(i_apply_only): opc[84].count++; goto lb_i_apply_only; \
CountCase(i_band_jId): opc[85].count++; goto lb_i_band_jId; \
CountCase(i_bif2_fbd): opc[86].count++; goto lb_i_bif2_fbd; \
CountCase(i_bif2_body_bd): opc[87].count++; goto lb_i_bif2_body_bd; \
CountCase(i_bor_jId): opc[88].count++; goto lb_i_bor_jId; \
CountCase(i_bs_add_jId): opc[89].count++; goto lb_i_bs_add_jId; \
CountCase(i_bs_append_jIIId): opc[90].count++; goto lb_i_bs_append_jIIId; \
CountCase(i_bs_bits_to_bytes_rjd): opc[91].count++; goto lb_i_bs_bits_to_bytes_rjd; \
CountCase(i_bs_bits_to_bytes_xjd): opc[92].count++; goto lb_i_bs_bits_to_bytes_xjd; \
CountCase(i_bs_bits_to_bytes_yjd): opc[93].count++; goto lb_i_bs_bits_to_bytes_yjd; \
CountCase(i_bs_get_binary2_frIsId): opc[94].count++; goto lb_i_bs_get_binary2_frIsId; \
CountCase(i_bs_get_binary2_fxIsId): opc[95].count++; goto lb_i_bs_get_binary2_fxIsId; \
CountCase(i_bs_get_binary_all2_frIId): opc[96].count++; goto lb_i_bs_get_binary_all2_frIId; \
CountCase(i_bs_get_binary_all2_fxIId): opc[97].count++; goto lb_i_bs_get_binary_all2_fxIId; \
CountCase(i_bs_get_binary_all_reuse_rfI): opc[98].count++; goto lb_i_bs_get_binary_all_reuse_rfI; \
CountCase(i_bs_get_binary_all_reuse_xfI): opc[99].count++; goto lb_i_bs_get_binary_all_reuse_xfI; \
CountCase(i_bs_get_binary_imm2_frIIId): opc[100].count++; goto lb_i_bs_get_binary_imm2_frIIId; \
CountCase(i_bs_get_binary_imm2_fxIIId): opc[101].count++; goto lb_i_bs_get_binary_imm2_fxIIId; \
CountCase(i_bs_get_float2_frIsId): opc[102].count++; goto lb_i_bs_get_float2_frIsId; \
CountCase(i_bs_get_float2_fxIsId): opc[103].count++; goto lb_i_bs_get_float2_fxIsId; \
CountCase(i_bs_get_integer_fIId): opc[104].count++; goto lb_i_bs_get_integer_fIId; \
CountCase(i_bs_get_integer_16_rfd): opc[105].count++; goto lb_i_bs_get_integer_16_rfd; \
CountCase(i_bs_get_integer_16_xfd): opc[106].count++; goto lb_i_bs_get_integer_16_xfd; \
CountCase(i_bs_get_integer_32_rfId): opc[107].count++; goto lb_i_bs_get_integer_32_rfId; \
CountCase(i_bs_get_integer_32_xfId): opc[108].count++; goto lb_i_bs_get_integer_32_xfId; \
CountCase(i_bs_get_integer_8_rfd): opc[109].count++; goto lb_i_bs_get_integer_8_rfd; \
CountCase(i_bs_get_integer_8_xfd): opc[110].count++; goto lb_i_bs_get_integer_8_xfd; \
CountCase(i_bs_get_integer_imm_rIIfId): opc[111].count++; goto lb_i_bs_get_integer_imm_rIIfId; \
CountCase(i_bs_get_integer_imm_xIIfId): opc[112].count++; goto lb_i_bs_get_integer_imm_xIIfId; \
CountCase(i_bs_get_integer_small_imm_rIfId): opc[113].count++; goto lb_i_bs_get_integer_small_imm_rIfId; \
CountCase(i_bs_get_integer_small_imm_xIfId): opc[114].count++; goto lb_i_bs_get_integer_small_imm_xIfId; \
CountCase(i_bs_get_utf16_rfId): opc[115].count++; goto lb_i_bs_get_utf16_rfId; \
CountCase(i_bs_get_utf16_xfId): opc[116].count++; goto lb_i_bs_get_utf16_xfId; \
CountCase(i_bs_get_utf8_rfd): opc[117].count++; goto lb_i_bs_get_utf8_rfd; \
CountCase(i_bs_get_utf8_xfd): opc[118].count++; goto lb_i_bs_get_utf8_xfd; \
CountCase(i_bs_init_IId): opc[119].count++; goto lb_i_bs_init_IId; \
CountCase(i_bs_init_bits_IId): opc[120].count++; goto lb_i_bs_init_bits_IId; \
CountCase(i_bs_init_bits_fail_rjId): opc[121].count++; goto lb_i_bs_init_bits_fail_rjId; \
CountCase(i_bs_init_bits_fail_xjId): opc[122].count++; goto lb_i_bs_init_bits_fail_xjId; \
CountCase(i_bs_init_bits_fail_yjId): opc[123].count++; goto lb_i_bs_init_bits_fail_yjId; \
CountCase(i_bs_init_bits_fail_heap_IjId): opc[124].count++; goto lb_i_bs_init_bits_fail_heap_IjId; \
CountCase(i_bs_init_bits_heap_IIId): opc[125].count++; goto lb_i_bs_init_bits_heap_IIId; \
CountCase(i_bs_init_fail_rjId): opc[126].count++; goto lb_i_bs_init_fail_rjId; \
CountCase(i_bs_init_fail_xjId): opc[127].count++; goto lb_i_bs_init_fail_xjId; \
CountCase(i_bs_init_fail_yjId): opc[128].count++; goto lb_i_bs_init_fail_yjId; \
CountCase(i_bs_init_fail_heap_IjId): opc[129].count++; goto lb_i_bs_init_fail_heap_IjId; \
CountCase(i_bs_init_heap_IIId): opc[130].count++; goto lb_i_bs_init_heap_IIId; \
CountCase(i_bs_init_heap_bin_IId): opc[131].count++; goto lb_i_bs_init_heap_bin_IId; \
CountCase(i_bs_init_heap_bin_heap_IIId): opc[132].count++; goto lb_i_bs_init_heap_bin_heap_IIId; \
CountCase(i_bs_match_string_rfII): opc[133].count++; goto lb_i_bs_match_string_rfII; \
CountCase(i_bs_match_string_xfII): opc[134].count++; goto lb_i_bs_match_string_xfII; \
CountCase(i_bs_private_append_jId): opc[135].count++; goto lb_i_bs_private_append_jId; \
CountCase(i_bs_put_utf16_jIs): opc[136].count++; goto lb_i_bs_put_utf16_jIs; \
CountCase(i_bs_put_utf8_js): opc[137].count++; goto lb_i_bs_put_utf8_js; \
CountCase(i_bs_restore2_rI): opc[138].count++; goto lb_i_bs_restore2_rI; \
CountCase(i_bs_restore2_xI): opc[139].count++; goto lb_i_bs_restore2_xI; \
CountCase(i_bs_save2_rI): opc[140].count++; goto lb_i_bs_save2_rI; \
CountCase(i_bs_save2_xI): opc[141].count++; goto lb_i_bs_save2_xI; \
CountCase(i_bs_skip_bits2_frxI): opc[142].count++; goto lb_i_bs_skip_bits2_frxI; \
CountCase(i_bs_skip_bits2_fryI): opc[143].count++; goto lb_i_bs_skip_bits2_fryI; \
CountCase(i_bs_skip_bits2_fxrI): opc[144].count++; goto lb_i_bs_skip_bits2_fxrI; \
CountCase(i_bs_skip_bits2_fxxI): opc[145].count++; goto lb_i_bs_skip_bits2_fxxI; \
CountCase(i_bs_skip_bits2_fxyI): opc[146].count++; goto lb_i_bs_skip_bits2_fxyI; \
CountCase(i_bs_skip_bits_all2_frI): opc[147].count++; goto lb_i_bs_skip_bits_all2_frI; \
CountCase(i_bs_skip_bits_all2_fxI): opc[148].count++; goto lb_i_bs_skip_bits_all2_fxI; \
CountCase(i_bs_skip_bits_imm2_frI): opc[149].count++; goto lb_i_bs_skip_bits_imm2_frI; \
CountCase(i_bs_skip_bits_imm2_fxI): opc[150].count++; goto lb_i_bs_skip_bits_imm2_fxI; \
CountCase(i_bs_start_match2_rfIId): opc[151].count++; goto lb_i_bs_start_match2_rfIId; \
CountCase(i_bs_start_match2_xfIId): opc[152].count++; goto lb_i_bs_start_match2_xfIId; \
CountCase(i_bs_start_match2_yfIId): opc[153].count++; goto lb_i_bs_start_match2_yfIId; \
CountCase(i_bs_utf16_size_sd): opc[154].count++; goto lb_i_bs_utf16_size_sd; \
CountCase(i_bs_utf8_size_sd): opc[155].count++; goto lb_i_bs_utf8_size_sd; \
CountCase(i_bs_validate_unicode_js): opc[156].count++; goto lb_i_bs_validate_unicode_js; \
CountCase(i_bs_validate_unicode_retract_j): opc[157].count++; goto lb_i_bs_validate_unicode_retract_j; \
CountCase(i_bsl_jId): opc[158].count++; goto lb_i_bsl_jId; \
CountCase(i_bsr_jId): opc[159].count++; goto lb_i_bsr_jId; \
CountCase(i_bxor_jId): opc[160].count++; goto lb_i_bxor_jId; \
CountCase(i_call_f): opc[161].count++; goto lb_i_call_f; \
CountCase(i_call_ext_e): opc[162].count++; goto lb_i_call_ext_e; \
CountCase(i_call_ext_last_eP): opc[163].count++; goto lb_i_call_ext_last_eP; \
CountCase(i_call_ext_only_e): opc[164].count++; goto lb_i_call_ext_only_e; \
CountCase(i_call_fun_I): opc[165].count++; goto lb_i_call_fun_I; \
CountCase(i_call_fun_last_IP): opc[166].count++; goto lb_i_call_fun_last_IP; \
CountCase(i_call_last_fP): opc[167].count++; goto lb_i_call_last_fP; \
CountCase(i_call_only_f): opc[168].count++; goto lb_i_call_only_f; \
CountCase(i_count_breakpoint): opc[169].count++; goto lb_i_count_breakpoint; \
CountCase(i_debug_breakpoint): opc[170].count++; goto lb_i_debug_breakpoint; \
CountCase(i_element_jssd): opc[171].count++; goto lb_i_element_jssd; \
CountCase(i_fadd_lll): opc[172].count++; goto lb_i_fadd_lll; \
CountCase(i_fast_element_jIsd): opc[173].count++; goto lb_i_fast_element_jIsd; \
CountCase(i_fcheckerror): opc[174].count++; goto lb_i_fcheckerror; \
CountCase(i_fdiv_lll): opc[175].count++; goto lb_i_fdiv_lll; \
CountCase(i_fetch_rx): opc[176].count++; goto lb_i_fetch_rx; \
CountCase(i_fetch_ry): opc[177].count++; goto lb_i_fetch_ry; \
CountCase(i_fetch_xr): opc[178].count++; goto lb_i_fetch_xr; \
CountCase(i_fetch_xx): opc[179].count++; goto lb_i_fetch_xx; \
CountCase(i_fetch_xy): opc[180].count++; goto lb_i_fetch_xy; \
CountCase(i_fetch_yr): opc[181].count++; goto lb_i_fetch_yr; \
CountCase(i_fetch_yx): opc[182].count++; goto lb_i_fetch_yx; \
CountCase(i_fetch_yy): opc[183].count++; goto lb_i_fetch_yy; \
CountCase(i_fetch_rc): opc[184].count++; goto lb_i_fetch_rc; \
CountCase(i_fetch_xc): opc[185].count++; goto lb_i_fetch_xc; \
CountCase(i_fetch_yc): opc[186].count++; goto lb_i_fetch_yc; \
CountCase(i_fetch_cr): opc[187].count++; goto lb_i_fetch_cr; \
CountCase(i_fetch_cx): opc[188].count++; goto lb_i_fetch_cx; \
CountCase(i_fetch_cy): opc[189].count++; goto lb_i_fetch_cy; \
CountCase(i_fetch_cc): opc[190].count++; goto lb_i_fetch_cc; \
CountCase(i_fetch_ss): opc[191].count++; goto lb_i_fetch_ss; \
CountCase(i_fmul_lll): opc[192].count++; goto lb_i_fmul_lll; \
CountCase(i_fnegate_ll): opc[193].count++; goto lb_i_fnegate_ll; \
CountCase(i_fsub_lll): opc[194].count++; goto lb_i_fsub_lll; \
CountCase(i_func_info_IaaI): opc[195].count++; goto lb_i_func_info_IaaI; \
CountCase(i_gc_bif1_jIsId): opc[196].count++; goto lb_i_gc_bif1_jIsId; \
CountCase(i_get_sd): opc[197].count++; goto lb_i_get_sd; \
CountCase(i_get_tuple_element_rPr): opc[198].count++; goto lb_i_get_tuple_element_rPr; \
CountCase(i_get_tuple_element_rPx): opc[199].count++; goto lb_i_get_tuple_element_rPx; \
CountCase(i_get_tuple_element_rPy): opc[200].count++; goto lb_i_get_tuple_element_rPy; \
CountCase(i_get_tuple_element_xPr): opc[201].count++; goto lb_i_get_tuple_element_xPr; \
CountCase(i_get_tuple_element_xPx): opc[202].count++; goto lb_i_get_tuple_element_xPx; \
CountCase(i_get_tuple_element_xPy): opc[203].count++; goto lb_i_get_tuple_element_xPy; \
CountCase(i_get_tuple_element_yPr): opc[204].count++; goto lb_i_get_tuple_element_yPr; \
CountCase(i_get_tuple_element_yPx): opc[205].count++; goto lb_i_get_tuple_element_yPx; \
CountCase(i_get_tuple_element_yPy): opc[206].count++; goto lb_i_get_tuple_element_yPy; \
CountCase(i_global_cons): opc[207].count++; goto lb_i_global_cons; \
CountCase(i_global_copy): opc[208].count++; goto lb_i_global_copy; \
CountCase(i_global_tuple): opc[209].count++; goto lb_i_global_tuple; \
CountCase(i_hibernate): opc[210].count++; goto lb_i_hibernate; \
CountCase(i_int_bnot_jsId): opc[211].count++; goto lb_i_int_bnot_jsId; \
CountCase(i_int_div_jId): opc[212].count++; goto lb_i_int_div_jId; \
CountCase(i_is_eq_f): opc[213].count++; goto lb_i_is_eq_f; \
CountCase(i_is_eq_exact_f): opc[214].count++; goto lb_i_is_eq_exact_f; \
CountCase(i_is_eq_immed_frc): opc[215].count++; goto lb_i_is_eq_immed_frc; \
CountCase(i_is_eq_immed_fxc): opc[216].count++; goto lb_i_is_eq_immed_fxc; \
CountCase(i_is_eq_immed_fyc): opc[217].count++; goto lb_i_is_eq_immed_fyc; \
CountCase(i_is_ge_f): opc[218].count++; goto lb_i_is_ge_f; \
CountCase(i_is_lt_f): opc[219].count++; goto lb_i_is_lt_f; \
CountCase(i_is_ne_f): opc[220].count++; goto lb_i_is_ne_f; \
CountCase(i_is_ne_exact_f): opc[221].count++; goto lb_i_is_ne_exact_f; \
CountCase(i_jump_on_val_sfII): opc[222].count++; goto lb_i_jump_on_val_sfII; \
CountCase(i_jump_on_val_zero_sfI): opc[223].count++; goto lb_i_jump_on_val_zero_sfI; \
CountCase(i_loop_rec_fr): opc[224].count++; goto lb_i_loop_rec_fr; \
CountCase(i_m_div_jId): opc[225].count++; goto lb_i_m_div_jId; \
CountCase(i_make_fun_It): opc[226].count++; goto lb_i_make_fun_It; \
CountCase(i_minus_jId): opc[227].count++; goto lb_i_minus_jId; \
CountCase(i_move_call_crf): opc[228].count++; goto lb_i_move_call_crf; \
CountCase(i_move_call_ext_cre): opc[229].count++; goto lb_i_move_call_ext_cre; \
CountCase(i_move_call_ext_last_ePcr): opc[230].count++; goto lb_i_move_call_ext_last_ePcr; \
CountCase(i_move_call_ext_only_ecr): opc[231].count++; goto lb_i_move_call_ext_only_ecr; \
CountCase(i_move_call_last_fPcr): opc[232].count++; goto lb_i_move_call_last_fPcr; \
CountCase(i_move_call_only_fcr): opc[233].count++; goto lb_i_move_call_only_fcr; \
CountCase(i_mtrace_breakpoint): opc[234].count++; goto lb_i_mtrace_breakpoint; \
CountCase(i_new_bs_put_binary_jsIs): opc[235].count++; goto lb_i_new_bs_put_binary_jsIs; \
CountCase(i_new_bs_put_binary_all_jsI): opc[236].count++; goto lb_i_new_bs_put_binary_all_jsI; \
CountCase(i_new_bs_put_binary_imm_jIs): opc[237].count++; goto lb_i_new_bs_put_binary_imm_jIs; \
CountCase(i_new_bs_put_float_jsIs): opc[238].count++; goto lb_i_new_bs_put_float_jsIs; \
CountCase(i_new_bs_put_float_imm_jIIs): opc[239].count++; goto lb_i_new_bs_put_float_imm_jIIs; \
CountCase(i_new_bs_put_integer_jsIs): opc[240].count++; goto lb_i_new_bs_put_integer_jsIs; \
CountCase(i_new_bs_put_integer_imm_jIIs): opc[241].count++; goto lb_i_new_bs_put_integer_imm_jIIs; \
CountCase(i_plus_jId): opc[242].count++; goto lb_i_plus_jId; \
CountCase(i_put_tuple_Anr): opc[243].count++; goto lb_i_put_tuple_Anr; \
CountCase(i_put_tuple_Anx): opc[244].count++; goto lb_i_put_tuple_Anx; \
CountCase(i_put_tuple_Arx): opc[245].count++; goto lb_i_put_tuple_Arx; \
CountCase(i_put_tuple_Ary): opc[246].count++; goto lb_i_put_tuple_Ary; \
CountCase(i_put_tuple_Axr): opc[247].count++; goto lb_i_put_tuple_Axr; \
CountCase(i_put_tuple_Axx): opc[248].count++; goto lb_i_put_tuple_Axx; \
CountCase(i_put_tuple_Axy): opc[249].count++; goto lb_i_put_tuple_Axy; \
CountCase(i_put_tuple_Ayr): opc[250].count++; goto lb_i_put_tuple_Ayr; \
CountCase(i_put_tuple_Ayx): opc[251].count++; goto lb_i_put_tuple_Ayx; \
CountCase(i_put_tuple_Ayy): opc[252].count++; goto lb_i_put_tuple_Ayy; \
CountCase(i_put_tuple_Acr): opc[253].count++; goto lb_i_put_tuple_Acr; \
CountCase(i_put_tuple_Acx): opc[254].count++; goto lb_i_put_tuple_Acx; \
CountCase(i_put_tuple_Acy): opc[255].count++; goto lb_i_put_tuple_Acy; \
CountCase(i_put_tuple_only_Ad): opc[256].count++; goto lb_i_put_tuple_only_Ad; \
CountCase(i_rem_jId): opc[257].count++; goto lb_i_rem_jId; \
CountCase(i_return_to_trace): opc[258].count++; goto lb_i_return_to_trace; \
CountCase(i_select_big_sf): opc[259].count++; goto lb_i_select_big_sf; \
CountCase(i_select_float_sfI): opc[260].count++; goto lb_i_select_float_sfI; \
CountCase(i_select_tuple_arity_sfI): opc[261].count++; goto lb_i_select_tuple_arity_sfI; \
CountCase(i_select_val_sfI): opc[262].count++; goto lb_i_select_val_sfI; \
CountCase(i_times_jId): opc[263].count++; goto lb_i_times_jId; \
CountCase(i_trace_breakpoint): opc[264].count++; goto lb_i_trace_breakpoint; \
CountCase(i_trim_I): opc[265].count++; goto lb_i_trim_I; \
CountCase(i_wait_error): opc[266].count++; goto lb_i_wait_error; \
CountCase(i_wait_error_locked): opc[267].count++; goto lb_i_wait_error_locked; \
CountCase(i_wait_timeout_fI): opc[268].count++; goto lb_i_wait_timeout_fI; \
CountCase(i_wait_timeout_fs): opc[269].count++; goto lb_i_wait_timeout_fs; \
CountCase(i_wait_timeout_locked_fI): opc[270].count++; goto lb_i_wait_timeout_locked_fI; \
CountCase(i_wait_timeout_locked_fs): opc[271].count++; goto lb_i_wait_timeout_locked_fs; \
CountCase(i_yield): opc[272].count++; goto lb_i_yield; \
CountCase(if_end): opc[273].count++; goto lb_if_end; \
CountCase(init_y): opc[274].count++; goto lb_init_y; \
CountCase(init2_yy): opc[275].count++; goto lb_init2_yy; \
CountCase(init3_yyy): opc[276].count++; goto lb_init3_yyy; \
CountCase(int_code_end): opc[277].count++; goto lb_int_code_end; \
CountCase(is_atom_fr): opc[278].count++; goto lb_is_atom_fr; \
CountCase(is_atom_fx): opc[279].count++; goto lb_is_atom_fx; \
CountCase(is_atom_fy): opc[280].count++; goto lb_is_atom_fy; \
CountCase(is_binary_fr): opc[281].count++; goto lb_is_binary_fr; \
CountCase(is_binary_fx): opc[282].count++; goto lb_is_binary_fx; \
CountCase(is_binary_fy): opc[283].count++; goto lb_is_binary_fy; \
CountCase(is_bitstring_fr): opc[284].count++; goto lb_is_bitstring_fr; \
CountCase(is_bitstring_fx): opc[285].count++; goto lb_is_bitstring_fx; \
CountCase(is_bitstring_fy): opc[286].count++; goto lb_is_bitstring_fy; \
CountCase(is_boolean_fr): opc[287].count++; goto lb_is_boolean_fr; \
CountCase(is_boolean_fx): opc[288].count++; goto lb_is_boolean_fx; \
CountCase(is_boolean_fy): opc[289].count++; goto lb_is_boolean_fy; \
CountCase(is_float_fr): opc[290].count++; goto lb_is_float_fr; \
CountCase(is_float_fx): opc[291].count++; goto lb_is_float_fx; \
CountCase(is_float_fy): opc[292].count++; goto lb_is_float_fy; \
CountCase(is_function_fr): opc[293].count++; goto lb_is_function_fr; \
CountCase(is_function_fx): opc[294].count++; goto lb_is_function_fx; \
CountCase(is_function_fy): opc[295].count++; goto lb_is_function_fy; \
CountCase(is_function2_fss): opc[296].count++; goto lb_is_function2_fss; \
CountCase(is_integer_fr): opc[297].count++; goto lb_is_integer_fr; \
CountCase(is_integer_fx): opc[298].count++; goto lb_is_integer_fx; \
CountCase(is_integer_fy): opc[299].count++; goto lb_is_integer_fy; \
CountCase(is_integer_allocate_frII): opc[300].count++; goto lb_is_integer_allocate_frII; \
CountCase(is_integer_allocate_fxII): opc[301].count++; goto lb_is_integer_allocate_fxII; \
CountCase(is_list_fr): opc[302].count++; goto lb_is_list_fr; \
CountCase(is_list_fx): opc[303].count++; goto lb_is_list_fx; \
CountCase(is_list_fy): opc[304].count++; goto lb_is_list_fy; \
CountCase(is_nil_fr): opc[305].count++; goto lb_is_nil_fr; \
CountCase(is_nil_fx): opc[306].count++; goto lb_is_nil_fx; \
CountCase(is_nil_fy): opc[307].count++; goto lb_is_nil_fy; \
CountCase(is_non_empty_list_test_heap_frII): opc[308].count++; goto lb_is_non_empty_list_test_heap_frII; \
CountCase(is_nonempty_list_fr): opc[309].count++; goto lb_is_nonempty_list_fr; \
CountCase(is_nonempty_list_fx): opc[310].count++; goto lb_is_nonempty_list_fx; \
CountCase(is_nonempty_list_fy): opc[311].count++; goto lb_is_nonempty_list_fy; \
CountCase(is_nonempty_list_allocate_frII): opc[312].count++; goto lb_is_nonempty_list_allocate_frII; \
CountCase(is_nonempty_list_allocate_fxII): opc[313].count++; goto lb_is_nonempty_list_allocate_fxII; \
CountCase(is_number_fr): opc[314].count++; goto lb_is_number_fr; \
CountCase(is_number_fx): opc[315].count++; goto lb_is_number_fx; \
CountCase(is_number_fy): opc[316].count++; goto lb_is_number_fy; \
CountCase(is_pid_fr): opc[317].count++; goto lb_is_pid_fr; \
CountCase(is_pid_fx): opc[318].count++; goto lb_is_pid_fx; \
CountCase(is_pid_fy): opc[319].count++; goto lb_is_pid_fy; \
CountCase(is_port_fr): opc[320].count++; goto lb_is_port_fr; \
CountCase(is_port_fx): opc[321].count++; goto lb_is_port_fx; \
CountCase(is_port_fy): opc[322].count++; goto lb_is_port_fy; \
CountCase(is_reference_fr): opc[323].count++; goto lb_is_reference_fr; \
CountCase(is_reference_fx): opc[324].count++; goto lb_is_reference_fx; \
CountCase(is_reference_fy): opc[325].count++; goto lb_is_reference_fy; \
CountCase(is_tuple_fr): opc[326].count++; goto lb_is_tuple_fr; \
CountCase(is_tuple_fx): opc[327].count++; goto lb_is_tuple_fx; \
CountCase(is_tuple_fy): opc[328].count++; goto lb_is_tuple_fy; \
CountCase(is_tuple_of_arity_frA): opc[329].count++; goto lb_is_tuple_of_arity_frA; \
CountCase(is_tuple_of_arity_fxA): opc[330].count++; goto lb_is_tuple_of_arity_fxA; \
CountCase(is_tuple_of_arity_fyA): opc[331].count++; goto lb_is_tuple_of_arity_fyA; \
CountCase(jump_f): opc[332].count++; goto lb_jump_f; \
CountCase(label_L): opc[333].count++; goto lb_label_L; \
CountCase(loop_rec_end_f): opc[334].count++; goto lb_loop_rec_end_f; \
CountCase(move_nr): opc[335].count++; goto lb_move_nr; \
CountCase(move_nx): opc[336].count++; goto lb_move_nx; \
CountCase(move_rx): opc[337].count++; goto lb_move_rx; \
CountCase(move_ry): opc[338].count++; goto lb_move_ry; \
CountCase(move_xr): opc[339].count++; goto lb_move_xr; \
CountCase(move_xx): opc[340].count++; goto lb_move_xx; \
CountCase(move_xy): opc[341].count++; goto lb_move_xy; \
CountCase(move_yr): opc[342].count++; goto lb_move_yr; \
CountCase(move_yx): opc[343].count++; goto lb_move_yx; \
CountCase(move_yy): opc[344].count++; goto lb_move_yy; \
CountCase(move_cr): opc[345].count++; goto lb_move_cr; \
CountCase(move_cx): opc[346].count++; goto lb_move_cx; \
CountCase(move_cy): opc[347].count++; goto lb_move_cy; \
CountCase(move_sd): opc[348].count++; goto lb_move_sd; \
CountCase(move2_xyxy): opc[349].count++; goto lb_move2_xyxy; \
CountCase(move2_yxyx): opc[350].count++; goto lb_move2_yxyx; \
CountCase(move_call_xrf): opc[351].count++; goto lb_move_call_xrf; \
CountCase(move_call_yrf): opc[352].count++; goto lb_move_call_yrf; \
CountCase(move_call_last_xrfP): opc[353].count++; goto lb_move_call_last_xrfP; \
CountCase(move_call_last_yrfP): opc[354].count++; goto lb_move_call_last_yrfP; \
CountCase(move_call_only_xrf): opc[355].count++; goto lb_move_call_only_xrf; \
CountCase(move_deallocate_return_nrP): opc[356].count++; goto lb_move_deallocate_return_nrP; \
CountCase(move_deallocate_return_xrP): opc[357].count++; goto lb_move_deallocate_return_xrP; \
CountCase(move_deallocate_return_yrP): opc[358].count++; goto lb_move_deallocate_return_yrP; \
CountCase(move_deallocate_return_crP): opc[359].count++; goto lb_move_deallocate_return_crP; \
CountCase(move_return_nr): opc[360].count++; goto lb_move_return_nr; \
CountCase(move_return_xr): opc[361].count++; goto lb_move_return_xr; \
CountCase(move_return_cr): opc[362].count++; goto lb_move_return_cr; \
CountCase(node_r): opc[363].count++; goto lb_node_r; \
CountCase(node_x): opc[364].count++; goto lb_node_x; \
CountCase(node_y): opc[365].count++; goto lb_node_y; \
CountCase(normal_exit): opc[366].count++; goto lb_normal_exit; \
CountCase(put_n): opc[367].count++; goto lb_put_n; \
CountCase(put_r): opc[368].count++; goto lb_put_r; \
CountCase(put_x): opc[369].count++; goto lb_put_x; \
CountCase(put_y): opc[370].count++; goto lb_put_y; \
CountCase(put_c): opc[371].count++; goto lb_put_c; \
CountCase(put_list_rnx): opc[372].count++; goto lb_put_list_rnx; \
CountCase(put_list_rxr): opc[373].count++; goto lb_put_list_rxr; \
CountCase(put_list_rxx): opc[374].count++; goto lb_put_list_rxx; \
CountCase(put_list_ryx): opc[375].count++; goto lb_put_list_ryx; \
CountCase(put_list_xnx): opc[376].count++; goto lb_put_list_xnx; \
CountCase(put_list_xrr): opc[377].count++; goto lb_put_list_xrr; \
CountCase(put_list_xxr): opc[378].count++; goto lb_put_list_xxr; \
CountCase(put_list_xxx): opc[379].count++; goto lb_put_list_xxx; \
CountCase(put_list_xyx): opc[380].count++; goto lb_put_list_xyx; \
CountCase(put_list_ynx): opc[381].count++; goto lb_put_list_ynx; \
CountCase(put_list_yrr): opc[382].count++; goto lb_put_list_yrr; \
CountCase(put_list_yrx): opc[383].count++; goto lb_put_list_yrx; \
CountCase(put_list_yxx): opc[384].count++; goto lb_put_list_yxx; \
CountCase(put_list_yyr): opc[385].count++; goto lb_put_list_yyr; \
CountCase(put_list_yyx): opc[386].count++; goto lb_put_list_yyx; \
CountCase(put_list_rcr): opc[387].count++; goto lb_put_list_rcr; \
CountCase(put_list_rcx): opc[388].count++; goto lb_put_list_rcx; \
CountCase(put_list_rcy): opc[389].count++; goto lb_put_list_rcy; \
CountCase(put_list_xcr): opc[390].count++; goto lb_put_list_xcr; \
CountCase(put_list_xcx): opc[391].count++; goto lb_put_list_xcx; \
CountCase(put_list_xcy): opc[392].count++; goto lb_put_list_xcy; \
CountCase(put_list_ycr): opc[393].count++; goto lb_put_list_ycr; \
CountCase(put_list_ycx): opc[394].count++; goto lb_put_list_ycx; \
CountCase(put_list_ycy): opc[395].count++; goto lb_put_list_ycy; \
CountCase(put_list_cnr): opc[396].count++; goto lb_put_list_cnr; \
CountCase(put_list_cnx): opc[397].count++; goto lb_put_list_cnx; \
CountCase(put_list_crr): opc[398].count++; goto lb_put_list_crr; \
CountCase(put_list_crx): opc[399].count++; goto lb_put_list_crx; \
CountCase(put_list_cry): opc[400].count++; goto lb_put_list_cry; \
CountCase(put_list_cxr): opc[401].count++; goto lb_put_list_cxr; \
CountCase(put_list_cxx): opc[402].count++; goto lb_put_list_cxx; \
CountCase(put_list_cxy): opc[403].count++; goto lb_put_list_cxy; \
CountCase(put_list_cyr): opc[404].count++; goto lb_put_list_cyr; \
CountCase(put_list_cyx): opc[405].count++; goto lb_put_list_cyx; \
CountCase(put_list_cyy): opc[406].count++; goto lb_put_list_cyy; \
CountCase(put_list_ssd): opc[407].count++; goto lb_put_list_ssd; \
CountCase(put_string_IId): opc[408].count++; goto lb_put_string_IId; \
CountCase(raise_ss): opc[409].count++; goto lb_raise_ss; \
CountCase(remove_message): opc[410].count++; goto lb_remove_message; \
CountCase(return): opc[411].count++; goto lb_return; \
CountCase(return_trace): opc[412].count++; goto lb_return_trace; \
CountCase(self_r): opc[413].count++; goto lb_self_r; \
CountCase(self_x): opc[414].count++; goto lb_self_x; \
CountCase(self_y): opc[415].count++; goto lb_self_y; \
CountCase(send): opc[416].count++; goto lb_send; \
CountCase(set_tuple_element_sdP): opc[417].count++; goto lb_set_tuple_element_sdP; \
CountCase(system_limit_j): opc[418].count++; goto lb_system_limit_j; \
CountCase(test_arity_frA): opc[419].count++; goto lb_test_arity_frA; \
CountCase(test_arity_fxA): opc[420].count++; goto lb_test_arity_fxA; \
CountCase(test_arity_fyA): opc[421].count++; goto lb_test_arity_fyA; \
CountCase(test_heap_II): opc[422].count++; goto lb_test_heap_II; \
CountCase(test_heap_1_put_list_Iy): opc[423].count++; goto lb_test_heap_1_put_list_Iy; \
CountCase(timeout): opc[424].count++; goto lb_timeout; \
CountCase(timeout_locked): opc[425].count++; goto lb_timeout_locked; \
CountCase(too_old_compiler): opc[426].count++; goto lb_too_old_compiler; \
CountCase(try_case_end_s): opc[427].count++; goto lb_try_case_end_s; \
CountCase(try_end_y): opc[428].count++; goto lb_try_end_y; \
CountCase(wait_f): opc[429].count++; goto lb_wait_f; \
CountCase(wait_locked_f): opc[430].count++; goto lb_wait_locked_f; \
CountCase(wait_unlocked_f): opc[431].count++; goto lb_wait_unlocked_f;

#define genop_label_1 1
#define genop_func_info_3 2
#define genop_int_code_end_0 3
#define genop_call_2 4
#define genop_call_last_3 5
#define genop_call_only_2 6
#define genop_call_ext_2 7
#define genop_call_ext_last_3 8
#define genop_bif0_2 9
#define genop_bif1_4 10
#define genop_bif2_5 11
#define genop_allocate_2 12
#define genop_allocate_heap_3 13
#define genop_allocate_zero_2 14
#define genop_allocate_heap_zero_3 15
#define genop_test_heap_2 16
#define genop_init_1 17
#define genop_deallocate_1 18
#define genop_return_0 19
#define genop_send_0 20
#define genop_remove_message_0 21
#define genop_timeout_0 22
#define genop_loop_rec_2 23
#define genop_loop_rec_end_1 24
#define genop_wait_1 25
#define genop_wait_timeout_2 26
#define genop_m_plus_4 27
#define genop_m_minus_4 28
#define genop_m_times_4 29
#define genop_m_div_4 30
#define genop_int_div_4 31
#define genop_int_rem_4 32
#define genop_int_band_4 33
#define genop_int_bor_4 34
#define genop_int_bxor_4 35
#define genop_int_bsl_4 36
#define genop_int_bsr_4 37
#define genop_int_bnot_3 38
#define genop_is_lt_3 39
#define genop_is_ge_3 40
#define genop_is_eq_3 41
#define genop_is_ne_3 42
#define genop_is_eq_exact_3 43
#define genop_is_ne_exact_3 44
#define genop_is_integer_2 45
#define genop_is_float_2 46
#define genop_is_number_2 47
#define genop_is_atom_2 48
#define genop_is_pid_2 49
#define genop_is_reference_2 50
#define genop_is_port_2 51
#define genop_is_nil_2 52
#define genop_is_binary_2 53
#define genop_is_constant_2 54
#define genop_is_list_2 55
#define genop_is_nonempty_list_2 56
#define genop_is_tuple_2 57
#define genop_test_arity_3 58
#define genop_select_val_3 59
#define genop_select_tuple_arity_3 60
#define genop_jump_1 61
#define genop_catch_2 62
#define genop_catch_end_1 63
#define genop_move_2 64
#define genop_get_list_3 65
#define genop_get_tuple_element_3 66
#define genop_set_tuple_element_3 67
#define genop_put_string_3 68
#define genop_put_list_3 69
#define genop_put_tuple_2 70
#define genop_put_1 71
#define genop_badmatch_1 72
#define genop_if_end_0 73
#define genop_case_end_1 74
#define genop_call_fun_1 75
#define genop_make_fun_3 76
#define genop_is_function_2 77
#define genop_call_ext_only_2 78
#define genop_bs_start_match_2 79
#define genop_bs_get_integer_5 80
#define genop_bs_get_float_5 81
#define genop_bs_get_binary_5 82
#define genop_bs_skip_bits_4 83
#define genop_bs_test_tail_2 84
#define genop_bs_save_1 85
#define genop_bs_restore_1 86
#define genop_bs_init_2 87
#define genop_bs_final_2 88
#define genop_bs_put_integer_5 89
#define genop_bs_put_binary_5 90
#define genop_bs_put_float_5 91
#define genop_bs_put_string_2 92
#define genop_bs_need_buf_1 93
#define genop_fclearerror_0 94
#define genop_fcheckerror_1 95
#define genop_fmove_2 96
#define genop_fconv_2 97
#define genop_fadd_4 98
#define genop_fsub_4 99
#define genop_fmul_4 100
#define genop_fdiv_4 101
#define genop_fnegate_3 102
#define genop_make_fun2_1 103
#define genop_try_2 104
#define genop_try_end_1 105
#define genop_try_case_1 106
#define genop_try_case_end_1 107
#define genop_raise_2 108
#define genop_bs_init2_6 109
#define genop_bs_bits_to_bytes_3 110
#define genop_bs_add_5 111
#define genop_apply_1 112
#define genop_apply_last_2 113
#define genop_is_boolean_2 114
#define genop_is_function2_3 115
#define genop_bs_start_match2_5 116
#define genop_bs_get_integer2_7 117
#define genop_bs_get_float2_7 118
#define genop_bs_get_binary2_7 119
#define genop_bs_skip_bits2_5 120
#define genop_bs_test_tail2_3 121
#define genop_bs_save2_2 122
#define genop_bs_restore2_2 123
#define genop_gc_bif1_5 124
#define genop_gc_bif2_6 125
#define genop_bs_final2_2 126
#define genop_bs_bits_to_bytes2_2 127
#define genop_put_literal_2 128
#define genop_is_bitstr_2 129
#define genop_bs_context_to_binary_1 130
#define genop_bs_test_unit_3 131
#define genop_bs_match_string_4 132
#define genop_bs_init_writable_0 133
#define genop_bs_append_8 134
#define genop_bs_private_append_6 135
#define genop_trim_2 136
#define genop_bs_init_bits_6 137
#define genop_bs_get_utf8_5 138
#define genop_bs_skip_utf8_4 139
#define genop_bs_get_utf16_5 140
#define genop_bs_skip_utf16_4 141
#define genop_bs_get_utf32_5 142
#define genop_bs_skip_utf32_4 143
#define genop_bs_utf8_size_3 144
#define genop_bs_put_utf8_3 145
#define genop_bs_utf16_size_3 146
#define genop_bs_put_utf16_3 147
#define genop_bs_put_utf32_3 148
#define genop_too_old_compiler_0 149
#define genop_i_func_info_4 150
#define genop_i_trace_breakpoint_0 151
#define genop_i_mtrace_breakpoint_0 152
#define genop_i_debug_breakpoint_0 153
#define genop_i_count_breakpoint_0 154
#define genop_i_return_to_trace_0 155
#define genop_i_yield_0 156
#define genop_i_global_cons_0 157
#define genop_i_global_tuple_0 158
#define genop_i_global_copy_0 159
#define genop_i_trim_1 160
#define genop_init2_2 161
#define genop_init3_3 162
#define genop_i_select_val_3 163
#define genop_i_select_tuple_arity_3 164
#define genop_i_select_big_2 165
#define genop_i_select_float_3 166
#define genop_i_jump_on_val_zero_3 167
#define genop_i_jump_on_val_4 168
#define genop_i_get_tuple_element_3 169
#define genop_badarg_1 170
#define genop_system_limit_1 171
#define genop_move2_4 172
#define genop_timeout_locked_0 173
#define genop_i_loop_rec_2 174
#define genop_wait_locked_1 175
#define genop_wait_unlocked_1 176
#define genop_i_wait_timeout_2 177
#define genop_i_wait_timeout_locked_2 178
#define genop_i_wait_error_0 179
#define genop_i_wait_error_locked_0 180
#define genop_i_is_lt_1 181
#define genop_i_is_ge_1 182
#define genop_i_is_eq_1 183
#define genop_i_is_ne_1 184
#define genop_i_is_eq_exact_1 185
#define genop_i_is_ne_exact_1 186
#define genop_i_is_eq_immed_3 187
#define genop_i_put_tuple_only_2 188
#define genop_i_put_tuple_3 189
#define genop_i_fetch_2 190
#define genop_normal_exit_0 191
#define genop_continue_exit_0 192
#define genop_apply_bif_0 193
#define genop_call_error_handler_0 194
#define genop_error_action_code_0 195
#define genop_call_traced_function_0 196
#define genop_return_trace_0 197
#define genop_move_return_2 198
#define genop_move_deallocate_return_3 199
#define genop_deallocate_return_1 200
#define genop_test_heap_1_put_list_2 201
#define genop_is_tuple_of_arity_3 202
#define genop_original_reg_2 203
#define genop_extract_next_element_1 204
#define genop_extract_next_element2_1 205
#define genop_extract_next_element3_1 206
#define genop_is_integer_allocate_4 207
#define genop_is_nonempty_list_allocate_4 208
#define genop_is_non_empty_list_test_heap_4 209
#define genop_is_bitstring_2 210
#define genop_allocate_init_3 211
#define genop_i_apply_0 212
#define genop_i_apply_last_1 213
#define genop_i_apply_only_0 214
#define genop_i_apply_fun_0 215
#define genop_i_apply_fun_last_1 216
#define genop_i_apply_fun_only_0 217
#define genop_i_hibernate_0 218
#define genop_call_bif0_1 219
#define genop_call_bif1_1 220
#define genop_call_bif2_1 221
#define genop_call_bif3_1 222
#define genop_i_get_2 223
#define genop_self_1 224
#define genop_node_1 225
#define genop_i_fast_element_4 226
#define genop_i_element_4 227
#define genop_bif1_body_3 228
#define genop_i_bif2_3 229
#define genop_i_bif2_body_2 230
#define genop_i_move_call_3 231
#define genop_move_call_3 232
#define genop_i_move_call_last_4 233
#define genop_move_call_last_4 234
#define genop_i_move_call_only_3 235
#define genop_move_call_only_3 236
#define genop_i_call_1 237
#define genop_i_call_last_2 238
#define genop_i_call_only_1 239
#define genop_i_call_ext_1 240
#define genop_i_call_ext_last_2 241
#define genop_i_call_ext_only_1 242
#define genop_i_move_call_ext_3 243
#define genop_i_move_call_ext_last_4 244
#define genop_i_move_call_ext_only_3 245
#define genop_i_call_fun_1 246
#define genop_i_call_fun_last_2 247
#define genop_i_make_fun_2 248
#define genop_i_bs_start_match2_5 249
#define genop_i_bs_save2_2 250
#define genop_i_bs_restore2_2 251
#define genop_i_bs_match_string_4 252
#define genop_i_bs_get_integer_small_imm_5 253
#define genop_i_bs_get_integer_imm_6 254
#define genop_i_bs_get_integer_4 255
#define genop_i_bs_get_integer_8_3 256
#define genop_i_bs_get_integer_16_3 257
#define genop_i_bs_get_integer_32_4 258
#define genop_i_bs_get_binary_imm2_6 259
#define genop_i_bs_get_binary2_6 260
#define genop_i_bs_get_binary_all2_5 261
#define genop_i_bs_get_binary_all_reuse_3 262
#define genop_i_bs_get_float2_6 263
#define genop_i_bs_skip_bits_imm2_3 264
#define genop_i_bs_skip_bits2_4 265
#define genop_i_bs_skip_bits_all2_3 266
#define genop_bs_test_zero_tail2_2 267
#define genop_bs_test_tail_imm2_3 268
#define genop_bs_test_unit8_2 269
#define genop_i_bs_get_utf8_3 270
#define genop_i_bs_get_utf16_4 271
#define genop_i_bs_validate_unicode_retract_1 272
#define genop_i_bs_init_fail_4 273
#define genop_i_bs_init_fail_heap_4 274
#define genop_i_bs_init_3 275
#define genop_i_bs_init_heap_bin_3 276
#define genop_i_bs_init_heap_4 277
#define genop_i_bs_init_heap_bin_heap_4 278
#define genop_i_bs_init_bits_fail_4 279
#define genop_i_bs_init_bits_fail_heap_4 280
#define genop_i_bs_init_bits_3 281
#define genop_i_bs_init_bits_heap_4 282
#define genop_i_bs_bits_to_bytes_3 283
#define genop_i_bs_add_3 284
#define genop_i_bs_append_5 285
#define genop_i_bs_private_append_3 286
#define genop_i_new_bs_put_integer_4 287
#define genop_i_new_bs_put_integer_imm_4 288
#define genop_i_bs_utf8_size_2 289
#define genop_i_bs_utf16_size_2 290
#define genop_i_bs_put_utf8_2 291
#define genop_i_bs_put_utf16_3 292
#define genop_i_bs_validate_unicode_2 293
#define genop_i_new_bs_put_float_4 294
#define genop_i_new_bs_put_float_imm_4 295
#define genop_i_new_bs_put_binary_4 296
#define genop_i_new_bs_put_binary_imm_3 297
#define genop_i_new_bs_put_binary_all_3 298
#define genop_i_fadd_3 299
#define genop_i_fsub_3 300
#define genop_i_fmul_3 301
#define genop_i_fdiv_3 302
#define genop_i_fnegate_2 303
#define genop_i_fcheckerror_0 304
#define genop_fmove_new_2 305
#define genop_i_plus_3 306
#define genop_i_minus_3 307
#define genop_i_times_3 308
#define genop_i_m_div_3 309
#define genop_i_int_div_3 310
#define genop_i_rem_3 311
#define genop_i_bsl_3 312
#define genop_i_bsr_3 313
#define genop_i_band_3 314
#define genop_i_bor_3 315
#define genop_i_bxor_3 316
#define genop_i_int_bnot_4 317
#define genop_i_gc_bif1_5 318
#define genop_hipe_trap_call_0 319
#define genop_hipe_trap_call_closure_0 320
#define genop_hipe_trap_return_0 321
#define genop_hipe_trap_throw_0 322
#define genop_hipe_trap_resume_0 323
#define genop_hipe_call_count_0 324
#endif
